### ISSUE TITLE
Request to add a site: readcomicsonline.ru

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#194]
# Request to add a site

Description | Data
---|---
Url to add | `https://readcomicsonline.ru/comic/the-flash-2016`

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.2
URL | `https://readcomicsonline.ru/comic/the-flash-2016`

**Comment by gromenauer** [comment]
Last chapters fails:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
  --destination Manga/ https://readcomicsonline.ru/comic/the-flash-2016 \
  --reverse-downloading
~~~

~~~
2019-07-08 16:52:18.669 | ERROR    | manga_py.cli:start:41 - An error has been caught in function 'start', process 'MainProcess' (8871), thread 'MainThread' (140395157829376):
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7fb049a86f28>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 96, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_hand...
                  └ <function _run_util at 0x7fb049a86d90>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 55, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7fb0487e58d0>
           │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_hand...
           └ <function _init_cli at 0x7fb049a86d08>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 43, in _init_cli
    cli_mode.start()
    │        └ <function Cli.start at 0x7fb049a866a8>
    └ <manga_py.cli.Cli object at 0x7fb0487e5828>
> File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/cli/__init__.py", line 41, in start
    self.parser.start()
    │    │      └ <function Parser.start at 0x7fb049a86400>
    │    └ <manga_py.parser.Parser object at 0x7fb0487e5860>
    └ <manga_py.cli.Cli object at 0x7fb0487e5828>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/parser.py", line 45, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'no_webp': True, 'rewrite_exists_archives': False, 'max_volumes': 0, 'reverse_downloading': True, 'zero_fill': True, 'not_ch...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7fb0487e5860>
    │    │        │       │    └ {'no_webp': True, 'rewrite_exists_archives': False, 'max_volumes': 0, 'reverse_downloading': True, 'zero_fill': True, 'not_ch...
    │    │        │       └ <manga_py.parser.Parser object at 0x7fb0487e5860>
    │    │        └ <function Provider.process at 0x7fb0441a8488>
    │    └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
    └ <manga_py.parser.Parser object at 0x7fb0487e5860>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 83, in process
    self.loop_chapters()
    │    └ <function Provider.loop_chapters at 0x7fb0441a8620>
    └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 114, in loop_chapters
    self._info.add_volume(self.chapter_for_json(), self.get_archive_path())
    │    │     │          │    │                   │    └ <function Provider.get_archive_path at 0x7fb0441a8840>
    │    │     │          │    │                   └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
    │    │     │          │    └ <function Base.chapter_for_json at 0x7fb04814de18>
    │    │     │          └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
    │    │     └ <function Info.add_volume at 0x7fb049a86048>
    │    └ <manga_py.info.Info object at 0x7fb0487e58d0>
    └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 163, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
            │                        │    └ <function Std.get_archive_name at 0x7fb0441a8f28>
            │                        └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
            └ <function remove_file_query_params at 0x7fb049a7c048>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/helpers/std.py", line 9, in get_archive_name
    idx = self.get_chapter_index()
          │    └ <function ReadComicsOnlineRu.get_chapter_index at 0x7fb0487e4598>
          └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/readcomicsonline_ru.py", line 7, in get_chapter_index
    chapter = self.re.search(r'/(\d+(?:[\.-_]\d+)?)$', self.chapter).group(1)
              │    │  │                                │    └ <property object at 0x7fb04885aea8>
              │    │  │                                └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>
              │    │  └ <function search at 0x7fb049f61d08>
              │    └ <module 're' from '~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/re.py'>
              └ <manga_py.providers.readcomicsonline_ru.ReadComicsOnlineRu object at 0x7fb0487e5ac8>

AttributeError: 'NoneType' object has no attribute 'group'
~~~

It should be the weird numbering:
~~~
The Flash (2016-) #Annual 2
The Flash (2016-) #Annual 1
The Flash (2016-) #73 
The Flash (2016-) #72 
...
~~~

**Comment by 1271** [comment]
Oh.. Thank you, I will check it.

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.0
URL | `https://readcomicsonline.ru/comic/the-flash-2016`
