### ISSUE TITLE
Arguments seem to fail in 1.8.4-rc.4

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#215]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.4-rc.4
URL | `https://mangasushi.net/manga/assassin-de-aru-ore-no-sutetasu-ga-yuusha-yori-mo-akiraka-ni-tsuyoi-nodaga/`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
   --show-current-chapter-info --destination ~/Manga/ \
   https://mangasushi.net/manga/assassin-de-aru-ore-no-sutetasu-ga-yuusha-yori-mo-akiraka-ni-tsuyoi-nodaga/
~~~

#### Additional context

~~~ py
2019-08-25 14:25:39.656 | ERROR    | __main__:<module>:10 - An error has been caught in function '<module>', process 'MainProcess' (20804), thread 'MainThread' (140374051895040):
Traceback (most recent call last):
> File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7fab5e7debf8>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 96, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_hand...
                  └ <function _run_util at 0x7fab5e7dea60>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/__init__.py", line 54, in _run_util
    _info = Info(parse_args)
            │    └ Namespace(cbz=True, debug=False, destination='Manga/', max_volumes=0, min_free_space=100, na...
            └ <class 'manga_py.info.Info'>
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/info.py", line 60, in __init__
    _args['_raw_params'] = ' '.join(argv)
    │                               └ ['~/.local/share/virtualenvs/0_bin-S-IZrhuG/bin/manga-py', '--cbz', '--zero-fill', '--rename-pages', '--no-webp', ...
    └ Namespace(cbz=True, debug=False, destination='Manga/', max_volumes=0, min_free_space=100, na...

TypeError: 'Namespace' object does not support item assignment
~~~

**Comment by 1271** [comment]
oh... sorry ...
One moment

**Comment by 1271** [comment]
The condition did not work
`_args = args.__ dict__ if args is Namespace else args`

**Comment by gromenauer** [comment]
Fixed :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.4-rc.5
URL | `https://mangasushi.net/manga/assassin-de-aru-ore-no-sutetasu-ga-yuusha-yori-mo-akiraka-ni-tsuyoi-nodaga/`
