### ISSUE TITLE
bug: didnt download from sensescans

### ISSUE THREAD

**Issue by paulolimac** [manga-py/manga-py#218]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Ubuntu 18.04
Python version | 3.6.8
Pip version | 19.2.3
Manga-py version | 1.8.3.1
URL | http://sensescans.com/reader/series/to_you_the_immortal/

#### To Reproduce:
Steps to reproduce the behaviour:
1. Step 1
Manga-py cant download anything from sensescans site: `manga-py --rename-pages --cbz --max-volumes=2 --reverse-downloading --zero-fill http://reader.sensescans.com/series/to_you_the_immortal/`
2. Step 2
But it works in other sites, like: `manga-py --rename-pages --cbz --max-volumes=2 --reverse-downloading --zero-fill https://mangakakalot.com/chapter/to_you_the_immortal/`
3. Step 3
The error outputed from Step 1 was:
```
/home/user/.local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
CF error! Unable to find Cloudflare cookies. Does the site actually have Cloudflare IUAM ("I'm Under Attack Mode") enabled?
2019-08-30 21:02:51.423 | ERROR    | manga_py.cli:start:41 - An error has been caught in function 'start', process 'MainProcess' (3036), thread 'MainThread' (139897936652096):
Traceback (most recent call last):
  File "/home/user/.local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f3c83184ae8>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/__init__.py", line 96, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_hand...
                  └ <function _run_util at 0x7f3c83184950>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/__init__.py", line 55, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7f3c84782208>
           │         └ ArgumentParser(prog='manga-py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_hand...
           └ <function _init_cli at 0x7f3c831848c8>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/__init__.py", line 43, in _init_cli
    cli_mode.start()
    │        └ <function Cli.start at 0x7f3c831842f0>
    └ <manga_py.cli.Cli object at 0x7f3c84782160>
> File "/home/user/.local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 41, in start
    self.parser.start()
    │    │      └ <function Parser.start at 0x7f3c83184048>
    │    └ <manga_py.parser.Parser object at 0x7f3c84782320>
    └ <manga_py.cli.Cli object at 0x7f3c84782160>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/parser.py", line 45, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'url': 'http://reader.sensescans.com/series/to_you_the_immortal/', 'name': '', 'destination': 'Manga', 'no_progress': False,...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7f3c84782320>
    │    │        │       │    └ {'url': 'http://reader.sensescans.com/series/to_you_the_immortal/', 'name': '', 'destination': 'Manga', 'no_progress': False,...
    │    │        │       └ <manga_py.parser.Parser object at 0x7f3c84782320>
    │    │        └ <function Provider.process at 0x7f3c7f1117b8>
    │    └ <manga_py.providers.read_powermanga_org.ReadPowerMangaOrg object at 0x7f3c84782748>
    └ <manga_py.parser.Parser object at 0x7f3c84782320>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/provider.py", line 84, in process
    self._storage['chapters'] = self._prepare_chapters(self.get_chapters())
    │    │                      │    │                 │    └ <function GoMangaCo.get_chapters at 0x7f3c7f1191e0>
    │    │                      │    │                 └ <manga_py.providers.read_powermanga_org.ReadPowerMangaOrg object at 0x7f3c84782748>
    │    │                      │    └ <function Base._prepare_chapters at 0x7f3c7f410ea0>
    │    │                      └ <manga_py.providers.read_powermanga_org.ReadPowerMangaOrg object at 0x7f3c84782748>
    │    └ {'cookies': {}, 'main_content': '', 'chapters': [], 'current_chapter': 0, 'current_file': 0, 'proxies': {}, 'domain_uri': 'ht...
    └ <manga_py.providers.read_powermanga_org.ReadPowerMangaOrg object at 0x7f3c84782748>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/providers/gomanga_co.py", line 24, in get_chapters
    return self._elements(self._chapters_selector)
           │    │         │    └ '.list .element .title a'
           │    │         └ <manga_py.providers.read_powermanga_org.ReadPowerMangaOrg object at 0x7f3c84782748>
           │    └ <function Std._elements at 0x7f3c7f114730>
           └ <manga_py.providers.read_powermanga_org.ReadPowerMangaOrg object at 0x7f3c84782748>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/providers/helpers/std.py", line 16, in _elements
    return self.document_fromstring(content, selector)
           │    │                   │        └ '.list .element .title a'
           │    │                   └ ''
           │    └ <staticmethod object at 0x7f3c7f337470>
           └ <manga_py.providers.read_powermanga_org.ReadPowerMangaOrg object at 0x7f3c84782748>
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/base_classes/static.py", line 20, in document_fromstring
    result = document_fromstring(body)  # todo
             │                   └ ''
             └ <function document_fromstring at 0x7f3c81621620>
  File "/home/user/.local/lib/python3.6/site-packages/lxml/html/__init__.py", line 764, in document_fromstring
    "Document is empty")

lxml.etree.ParserError: Document is empty
```

#### Additional context
I'm running under a python environment.

**Comment by gromenauer** [comment]
@paulolimac, could you try version `1.8.5-rc.2` and let us know the result?

For me it's working OK:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.5-rc.2
URL | `http://sensescans.com/reader/series/to_you_the_immortal/`

**Comment by paulolimac** [comment]
@gromenauer and @1271, the 1.8.5-rc.2 (https://github.com/manga-py/manga-py/commit/7134d9bf66fa974181514ea7941921ebc7b8a4ec) worked like a charm!

And, strange and fortunately, the 1.8.4 (https://github.com/manga-py/manga-py/commit/67b769af6b6883ea1b6dcc4cf94d735d50f504b7) worked now too, after I retried some days ago.

Thank you, guys!
