### ISSUE TITLE
Bug: webtoons 

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#253]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.11.0
URL | `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
  --destination "Manga" --name "the_gamer" --show-current-chapter-info \
  "https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" 
~~~

#### Additional context
Error in the output

~~~
Parse chapters. Please, wait
Error processing file: vol_000-season-4-ep-102
Error processing file: vol_001-season-4-ep-103
Error processing file: vol_002-season-4-ep-104
Error processing file: vol_003-season-4-ep-105
Error processing file: vol_004-season-4-ep-106
Error processing file: vol_005-season-4-ep-107
Error processing file: vol_006-season-4-ep-108
Error processing file: vol_007-season-4-ep-109
Error processing file: vol_008-season-4-ep-110
Error processing file: vol_009-season-4-ep-111
~~~

**Comment by 1271** [comment]
I'll see today. Thanks for the issue

**Comment by 1271** [comment]
Hmm.. I can’t reproduce it

**Comment by 1271** [comment]
Hmm.. I can’t reproduce it

**Comment by gromenauer** [comment]
Tried on docker:

~~~ bash
docker pull mangadl/manga-py
docker run -it mangadl/manga-py
manga-py --version
# 1.11.0
manga-py "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" 
~~~
~~~
Parse chapters. Please, wait
Error processing file: vol_000-season-4-ep-102
Error processing file: vol_001-season-4-ep-103
Error processing file: vol_002-season-4-ep-104
Error processing file: vol_003-season-4-ep-105
Error processing file: vol_004-season-4-ep-106
Error processing file: vol_005-season-4-ep-107
Error processing file: vol_006-season-4-ep-108
Error processing file: vol_007-season-4-ep-109
Error processing file: vol_008-season-4-ep-110
Error processing file: vol_009-season-4-ep-111
~~~

Don't know if this helps in the debugging:
~~~ bash
wget "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" -O gamer.txt
wget "https://www.webtoons.com/en/fantasy/the-gamer/season-4-ep-111/viewer?title_no=88&episode_no=307" -O gamer_ep_307.txt
~~~

[gamer.txt](https://github.com/manga-py/manga-py/files/4003322/gamer.txt)
[gamer_ep_307.txt](https://github.com/manga-py/manga-py/files/4003324/gamer_ep_307.txt)

**Comment by 1271** [comment]
Thx

Please, try with --debug option
It's disable `try` and show error

**Comment by gromenauer** [comment]
Sorry nothing useful here:
~~~ bash
docker run -it mangadl/manga-py
manga-py --debug "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" 
~~~
~~~
Parse chapters. Please, wait
Error processing file: vol_000-season-4-ep-103
Error processing file: vol_001-season-4-ep-104
Error processing file: vol_002-season-4-ep-105
Error processing file: vol_003-season-4-ep-106
Error processing file: vol_004-season-4-ep-107
Error processing file: vol_005-season-4-ep-108
Error processing file: vol_006-season-4-ep-109
Error processing file: vol_007-season-4-ep-110
Error processing file: vol_008-season-4-ep-111
Error processing file: vol_009-season-4-ep-112
~~~

Is `--debug` in `1.12.0`? Docker is one version behind, tried to upgrade, but docker image have an inmutable cache (See https://github.com/manga-py/manga-py-docker/pull/1 for a fix).

**Comment by 1271** [comment]
Hmm.. Second

Not sure if cache is a problem, but added)

**Comment by 1271** [comment]
![image](https://user-images.githubusercontent.com/1452243/71527085-e3f27f00-28ea-11ea-814b-49e9330d794c.png)
The most interesting thing is that the images are present in the file that you sent

**Comment by 1271** [comment]
Please try to download [archive](https://github.com/manga-py/manga-py/archive/stable_1.x.zip) from git and run
I added save pages
If not difficult, send the archive here

**Comment by gromenauer** [comment]
Debugging with pudb
~~~
225     def html_fromstring(self, url, selector: str = None, idx: int = None):

url: 'https://www.webtoons.com/en/fantasy/the-gamer/season-4-ep-105/viewer?title_no=88&episode_no=301'

Return: HtmlElement [all]
| <empty>: 
~~~
It's a mistery to me :/

OK. Will try git version

**Comment by 1271** [comment]
> Return: HtmlElement [all]
| <empty>: 

Yeah. Crawler does not see the image

**Comment by gromenauer** [comment]
I'm doing something wrong here:
~~~ bash
git pull upstream stable_1.x
python manga.py --debug "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88"
Traceback (most recent call last):
  File "manga.py", line 4, in <module>
    from manga_py import main
  File "~/git/manga-py/manga_py/__init__.py", line 25
    print('Setup in progress?', file=stderr)
                                    ^
SyntaxError: invalid syntax
~~~

**Comment by 1271** [comment]
use python3, please :D

**Comment by gromenauer** [comment]
Ouch X)
~~~ bash
python3 manga.py --debug "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" 
Setup in progress?
Setup in progress?
Traceback (most recent call last):
  File "manga.py", line 8, in <module>
    main()
TypeError: 'NoneType' object is not callable
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "~/git/manga-py/manga_py/__init__.py", line 34, in before_shutdown
    temp_dir = get_temp_path()
NameError: name 'get_temp_path' is not defined
~~~

**Comment by 1271** [comment]
```bash
python3 -mvenv venv
. venv/bin/activate
pip install -r requirements.txt
```

**Comment by gromenauer** [comment]
Don't know if any advance
~~~ py
python3 manga.py --debug "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" 
Parse chapters. Please, wait
2019-12-27 19:18:31.540 | ERROR    | manga_py.cli:start:44 - An error has been caught in function 'start', process 'MainProcess' (7867), thread 'MainThread' (140532009989888):
Traceback (most recent call last):

  File "manga.py", line 8, in <module>
    main()
    └ <function main at 0x7fd0248040d0>

  File "~/git/manga-py/manga_py/__init__.py", line 96, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading...
                  └ <function _run_util at 0x7fd02482aea0>

  File "~/git/manga-py/manga_py/__init__.py", line 55, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7fd024785940>
           │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading...
           └ <function _init_cli at 0x7fd02482ae18>

  File "~/git/manga-py/manga_py/__init__.py", line 43, in _init_cli
    cli_mode.start()
    │        └ <function Cli.start at 0x7fd02482a6a8>
    └ <manga_py.cli.Cli object at 0x7fd024785860>

> File "~/git/manga-py/manga_py/cli/__init__.py", line 44, in start
    self.parser.start()
    │    │      └ <function Parser.start at 0x7fd02482a400>
    │    └ <manga_py.parser.Parser object at 0x7fd0247859b0>
    └ <manga_py.cli.Cli object at 0x7fd024785860>

  File "~/git/manga-py/manga_py/parser.py", line 45, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'skip_volumes': 0, 'no_progress': False, 'reverse_downloading': False, 'min_free_space': 100, 'override_archive_name': '', '...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7fd0247859b0>
    │    │        │       │    └ {'skip_volumes': 0, 'no_progress': False, 'reverse_downloading': False, 'min_free_space': 100, 'override_archive_name': '', '...
    │    │        │       └ <manga_py.parser.Parser object at 0x7fd0247859b0>
    │    │        └ <function Provider.process at 0x7fd021d1ad08>
    │    └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7fd024785d30>
    └ <manga_py.parser.Parser object at 0x7fd0247859b0>

  File "~/git/manga-py/manga_py/provider.py", line 96, in process
    self.loop_chapters()
    │    └ <function Provider.loop_chapters at 0x7fd021d1aea0>
    └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7fd024785d30>

  File "~/git/manga-py/manga_py/provider.py", line 129, in loop_chapters
    self._download_chapter()
    │    └ <function Provider._download_chapter at 0x7fd021d1ae18>
    └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7fd024785d30>

  File "~/git/manga-py/manga_py/provider.py", line 114, in _download_chapter
    raise e

  File "~/git/manga-py/manga_py/provider.py", line 109, in _download_chapter
    self._storage['files'] = self.get_files()
    │    │                   │    └ <function WebToonsCom.get_files at 0x7fd021d1e6a8>
    │    │                   └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7fd024785d30>
    │    └ {'cookies': {'locale': 'en', 'needGDPR': 'true'}, 'current_file': 0, 'current_chapter': 0, 'manga_name': 'the-gamer', 'domain...
    └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7fd024785d30>

  File "~/git/manga-py/manga_py/providers/webtoons_com.py", line 72, in get_files
    self.__debug_archive.writestr(content, 'page-{}'.format(self.chapter_id))
    │                             │                         │    └ <property object at 0x7fd0221f4908>
    │                             │                         └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7fd024785d30>
    │                             └ '\n\n\n\n\n\n<!doctype html>\n<html>\n<head>\n\t<title>WEBTOON - The official home for all things WEBTOON</title>\n\t\n\n\n\n...
    └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7fd024785d30>

  File "/usr/lib/python3.5/zipfile.py", line 1581, in writestr
    self.fp.write(zinfo.FileHeader(zip64))
    │    │  │     │     │          └ False
    │    │  │     │     └ <function ZipInfo.FileHeader at 0x7fd02477dd08>
    │    │  │     └ <ZipInfo filename='\n\n\n\n\n\n<!doctype html>\n<html>\n<head>\n\t<title>WEBTOON - The official home for all things WEBTOON</...
    │    │  └ <function _Tellable.write at 0x7fd0247a68c8>
    │    └ <zipfile._Tellable object at 0x7fd024785cc0>
    └ <zipfile.ZipFile file=<zipfile._Tellable object at 0x7fd024785cc0> mode='w'>
  File "/usr/lib/python3.5/zipfile.py", line 680, in write
    n = self.fp.write(data)
        │    │        └ b'PK\x03\x04\x14\x00\x00\x08\x08\x00O\x9a\x9bO\xad^\xac\xf0\x08\x00\x00\x00\x06\x00\x00\x00\xbe%\x00\x00\n\n\n\n\n\n<!doctype...
        │    └ PosixPath('~/git/manga-py/debug-WebToonsCom.zip')
        └ <zipfile._Tellable object at 0x7fd024785cc0>

AttributeError: 'PosixPath' object has no attribute 'write'
 
Exception ignored in: <bound method ZipFile.__del__ of <zipfile.ZipFile [closed]>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/zipfile.py", line 1595, in __del__
    self.close()
  File "/usr/lib/python3.5/zipfile.py", line 1608, in close
    self._write_end_record()
  File "/usr/lib/python3.5/zipfile.py", line 1711, in _write_end_record
    self.fp.write(endrec)
  File "/usr/lib/python3.5/zipfile.py", line 680, in write
    n = self.fp.write(data)
AttributeError: 'PosixPath' object has no attribute 'write'

~~~

**Comment by 1271** [comment]
Oh... My bad. Second... 

Done

`--debug` not need now )

**Comment by gromenauer** [comment]
~~~ bash
python3 manga.py --debug "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" 
Parse chapters. Please, wait
Error processing file: vol_000-season-4-ep-103
Error processing file: vol_001-season-4-ep-104
Error processing file: vol_002-season-4-ep-105
Error processing file: vol_003-season-4-ep-106
Error processing file: vol_004-season-4-ep-107
Error processing file: vol_005-season-4-ep-108
Error processing file: vol_006-season-4-ep-109
Error processing file: vol_007-season-4-ep-110
Error processing file: vol_008-season-4-ep-111
Error processing file: vol_009-season-4-ep-112
~~~

File is totally borked :rofl: 
~~~
7z l debug-WebToonsCom.zip 

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=es_ES.UTF-8,Utf16=on,HugeFiles=on,2 CPUs)

Listing archive: debug-WebToonsCom.zip

--
Path = debug-WebToonsCom.zip
Type = zip
Physical Size = 194102

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2019-12-27 19:24:26 .....            6            8  





<!doctype html>
<html>
<head>
	<title>WEBTOON - The official home for all things WEBTOON</title>
	






<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
...
~~~

**Comment by 1271** [comment]
Oh.. One moment )

**Comment by gromenauer** [comment]
Something like... https://stackoverflow.com/questions/18457678/python-write-in-memory-zip-to-file

**Comment by 1271** [comment]
It just doesn't close automatically.
Give me a sec.

**Comment by 1271** [comment]
Done. (I need to sleep more :D)

**Comment by gromenauer** [comment]
Don't sweat it. Live coding is hard (At least for me).

When it works, don't throw the code. Maybe usable for a `--provider_support_debug` flag if it can be abstracted to other providers.

Write it to a regular file (or two) if you want.

**Comment by 1271** [comment]
Something like this will be in v2
I don’t quite understand how to add this to the current implementation without changing all providers

**Comment by gromenauer** [comment]
Debug files are here (somehow). Find `<!doctype html>` for the beginning of each.

[test.txt](https://github.com/manga-py/manga-py/files/4006038/test.txt)

**Comment by 1271** [comment]
It would be better if the archive. But thanks)

**Comment by gromenauer** [comment]
Seems interesting, but not sure how to fix the zip.

**Comment by 1271** [comment]
![image](https://user-images.githubusercontent.com/1452243/71529110-240a2f80-28f4-11ea-9433-76a97f292800.png)
Seriously? 😕 
Did not see a similar page for me.
Perhaps this warning is relevant only for your country?

it looks as weird as possible

**Comment by 1271** [comment]
Please try to open the site in a private window of your browser.

**Comment by 1271** [comment]
Yeah....
![image](https://user-images.githubusercontent.com/1452243/71529262-1608de80-28f5-11ea-8184-2da723806702.png)

give me a second

**Comment by gromenauer** [comment]
Neded to clean cookies to see https://www.webtoons.com/en/ageGate

**Comment by 1271** [comment]
Yeah )
Try it now


i release it, if worked )

**Comment by gromenauer** [comment]
Works! 

Minor bug. Tried `--reverse-downloading` `-c 1` and it downloads more then one
~~~ bash
python3 manga.py --debug "http://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88" --reverse-downloading -c 1
~~~

**Comment by 1271** [comment]
Fixed.
@paulolimac changed the keys. Returned
