### ISSUE TITLE
Redirection: mangalife.us → manga4life.com

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#260]
# Request to redirect a site

Seems that `mangalife.us` no longer exists and now `manga4life.com` substitutes it.

Description | Old | New
---|---|---
Url to redirect |`http://mangalife.us`| `https://manga4life.com`

Example:
`http://mangalife.us/manga/Goblin-Slayer` → `https://manga4life.com/manga/Goblin-Slayer`

**Comment by gromenauer** [comment]
What you think about implementing a `-p` or `--force-provider` flag to force using a specific provider in a URL? 

In this case it would solve it with:

~~~ bash
manga-py \
  --force-provider http://mangalife.us \
  https://manga4life.com/manga/Goblin-Slayer
~~~

Too complicated?
It could ease issues adding new providers. (... Tried provider xxx in url yyy and works OK ...)

(Maybe I'm repeating myself here... ?!?, not sure)

**Comment by 1271** [comment]
> What you think about implementing a -p or --force-provider flag to force using a specific provider in a URL?
Too complicated?

No, it’s not difficult.
I will do it soon.
Sorry, work piled on me again :smile:

**Comment by gromenauer** [comment]
🦠 COVID-19 isolated? remote working?

**Comment by 1271** [comment]
Yes that's right.
Sory, we are now opening several offices in other countries. A lot of work.
I'll be back to manga-py soon

Take care of yourself!

**Comment by gromenauer** [comment]
Seems to be failing

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.14.2
URL | `https://manga4life.com/manga/Goblin-Slayer`

Tried in docker. Same error:

~~~ py
docker run -i --rm mangadl/manga-py

manga-py --version
Please remember that all sites earn on advertising.
Remember to visit them from your browser.
Thanks!

1.14.2

manga-py http://mangalife.us/manga/Goblin-Slayer
 
Please remember that all sites earn on advertising.
Remember to visit them from your browser.
Thanks!

2020-04-11 00:08:08.733 | ERROR    | manga_py.cli:start:47 - An error has been caught in function 'start', process 'MainProcess' (6), thread 'MainThread' (139969883805504):
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7f4d464728c8>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/manga_py/__init__.py", line 104, in main
    code, _info = _run_util(args)
                  │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading...
                  └ <function _run_util at 0x7f4d46472730>
  File "/usr/local/lib/python3.6/site-packages/manga_py/__init__.py", line 56, in _run_util
    code = _init_cli(args, _info)
           │         │     └ <manga_py.info.Info object at 0x7f4d45f00198>
           │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading...
           └ <function _init_cli at 0x7f4d464726a8>
  File "/usr/local/lib/python3.6/site-packages/manga_py/__init__.py", line 44, in _init_cli
    cli_mode.start()
    │        └ <function Cli.start at 0x7f4d46456ea0>
    └ <manga_py.cli.Cli object at 0x7f4d45f001d0>
> File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    │    │      └ <function Parser.start at 0x7f4d46456bf8>
    │    └ <manga_py.parser.Parser object at 0x7f4d45f00160>
    └ <manga_py.cli.Cli object at 0x7f4d45f001d0>
  File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 47, in start
    self.provider.process(self.params['url'], self.params)
    │    │        │       │    │              │    └ {'url': 'http://mangalife.us/manga/Goblin-Slayer', 'name': '', 'destination': 'Manga', 'no_progress': False, 'not_change_file...
    │    │        │       │    │              └ <manga_py.parser.Parser object at 0x7f4d45f00160>
    │    │        │       │    └ {'url': 'http://mangalife.us/manga/Goblin-Slayer', 'name': '', 'destination': 'Manga', 'no_progress': False, 'not_change_file...
    │    │        │       └ <manga_py.parser.Parser object at 0x7f4d45f00160>
    │    │        └ <function Provider.process at 0x7f4d43fdd0d0>
    │    └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7f4d45f00400>
    └ <manga_py.parser.Parser object at 0x7f4d45f00160>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 85, in process
    self._storage['manga_name'] = self.get_manga_name()
    │    │                        │    └ <function MangaLifeUs.get_manga_name at 0x7f4d44181488>
    │    │                        └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7f4d45f00400>
    │    └ {'cookies': {}, 'main_content': None, 'chapters': [], 'current_chapter': 0, 'current_file': 0, 'proxies': {}, 'domain_uri': N...
    └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7f4d45f00400>
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/mangalife_us.py", line 25, in get_manga_name
    test = self.re.search(r'\.\w{2,7}/read-online/')
           │    │  └ <function search at 0x7f4d46fe7b70>
           │    └ <module 're' from '/usr/local/lib/python3.6/re.py'>
           └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7f4d45f00400>

TypeError: search() missing 1 required positional argument: 'string'


~~~

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.18.1
URL | `http://mangalife.us/manga/Goblin-Slayer`
URL | `https://manga4life.com/manga/Goblin-Slayer`

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD/:/home/manga/Manga \
  mangadl/manga-py manga-py \
  --destination /home/manga/Manga \
  --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info \
  http://mangalife.us/manga/Goblin-Slayer -c 3
~~~
~~~
100% (25 of 25) |##############################| Elapsed Time: 0:00:09 Time:  0:00:09
100% (25 of 25) |##############################| Elapsed Time: 0:01:52 Time:  0:01:52
100% (36 of 36) |##############################| Elapsed Time: 0:00:06 Time:  0:00:06
 100% (36 of 36) |##############################| Elapsed Time: 0:00:06 Time:  0:00:06
~~~
~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD/:/home/manga/Manga \
  mangadl/manga-py manga-py \
  --destination /home/manga/Manga \
  --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info \
  https://manga4life.com/manga/Goblin-Slayer -c 3
~~~
~~~
100% (25 of 25) |##############################| Elapsed Time: 0:00:05 Time:  0:00:05
100% (23 of 23) |##############################| Elapsed Time: 0:00:06 Time:  0:00:06
100% (36 of 36) |##############################| Elapsed Time: 0:00:06 Time:  0:00:06
~~~
