### ISSUE TITLE
Redirection heavenmanga.vip →heaventoon.com

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#279]
# Request to add a site redirection

Old site | New site
---|---
`http://heavenmanga.vip` | `http://heaventoon.com`

This works (redirection is fine):
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info --destination Manga/ \
  --force-provider http://heavenmanga.vip/denma/ \
   http://heaventoon.com/denma/ 
~~~

But I catched a bug: Chapter 1.2 overlaps chapter 12 
strangely it get's download, but not json printed:
~~~
Current chapter url: http://heaventoon.com/denma-chap

Error processing file: vol_000-0


Current chapter url: http://heaventoon.com/denma-chap-1

 50% (2 of 4) |###################| Elapsed Time: 0:00:01 ETA:   0:00:01

Current chapter url: http://heaventoon.com/denma-chap-12

100% (4 of 4) |###################| Elapsed Time: 0:00:03 Time:  0:00:03
100% (7 of 7) |###################| Elapsed Time: 0:00:02 Time:  0:00:02
~~~

~~~ bash
manga-py http://heaventoon.com/denma/ --simulate --print-json  \
  --force-provider http://heavenmanga.vip/denma/
~~~
~~~ json
...
  "volumes": [
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_000-0.cbz",
      "url": "http://heaventoon.com/denma-chap"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_002-0.cbz",
      "url": "http://heaventoon.com/denma-chap-2"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_003-0.cbz",
      "url": "http://heaventoon.com/denma-chap-3"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_004-0.cbz",
      "url": "http://heaventoon.com/denma-chap-4"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_005-0.cbz",
      "url": "http://heaventoon.com/denma-chap-5"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_006-0.cbz",
      "url": "http://heaventoon.com/denma-chap-6"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_007-0.cbz",
      "url": "http://heaventoon.com/denma-chap-7"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_008-0.cbz",
      "url": "http://heaventoon.com/denma-chap-8"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_009-0.cbz",
      "url": "http://heaventoon.com/denma-chap-9"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_010-0.cbz",
      "url": "http://heaventoon.com/denma-chap-10"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_011-0.cbz",
      "url": "http://heaventoon.com/denma-chap-11"
    },
    {
      "error": false,
      "error_message": "",
      "path": "/home/alicia/Descargas/Pendiente/Manga/denma/vol_013-0.cbz",
      "url": "http://heaventoon.com/denma-chap-13"
    },
...
~~~

**Comment by 1271** [comment]
Yeah. But it's not manga-py bug:

![изображение](https://user-images.githubusercontent.com/1452243/79601330-4f0dce80-80f1-11ea-89ee-533f63f0d6b1.png)

And.. I see chapter 1.2 for me:

```json
"volumes": [
    {
      "error": false,
      "error_message": "",
      "path": "Manga/denma/vol_000-0.cbz",
      "url": "http://heaventoon.com/denma-chap"
    },
    {
      "error": false,
      "error_message": "",
      "path": "Manga/denma/vol_001-0.cbz",
      "url": "http://heaventoon.com/denma-chap-1"
    },
    {
      "error": false,
      "error_message": "",
      "path": "Manga/denma/vol_012-0.cbz",
      "url": "http://heaventoon.com/denma-chap-12"
    },
    {
      "error": false,
      "error_message": "",
      "path": "Manga/denma/vol_002-0.cbz",
      "url": "http://heaventoon.com/denma-chap-2"
    },
...

    {
      "error": false,
      "error_message": "",
      "path": "Manga/denma/vol_011-0.cbz",
      "url": "http://heaventoon.com/denma-chap-11"
    },
    {
      "error": false,
      "error_message": "",
      "path": "Manga/denma/vol_012-0.cbz",
      "url": "http://heaventoon.com/denma-chap-12"
    },
    {
      "error": false,
      "error_message": "",
      "path": "Manga/denma/vol_013-0.cbz",
      "url": "http://heaventoon.com/denma-chap-13"
    },
...
```

 ̶U̶r̶l̶ ̶c̶h̶a̶n̶g̶e̶d̶.̶ ̶T̶h̶a̶n̶k̶s

Wait. heavenmanga  have pattern \w+:

Try it without `force` key

https://github.com/manga-py/manga-py/blob/41c761d76b5314b62ac3dc4b7e9c5e12f0393235/manga_py/providers/__init__.py#L139-L141

**Comment by gromenauer** [comment]
No force → Provider not found

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.18.1
URL | `http://heaventoon.com/denma/`


~~~ bash
docker run --interactive --tty --rm --name manga-py -v $PWD/:/home/manga/Manga mangadl/manga-py \
  manga-py --destination /home/manga/Manga --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
    http://heaventoon.com/denma/ --simulate --print-json
~~~
~~~
"ERROR:/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py:44:2020-04-26 14:36:56,625:Please check if your inputed domain is supported by manga-py: 
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
- https://yuru-yuri.github.io/manga-py/ (deprecated)
Make sure that your inputed URL is correct
Trace:"
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │        └ <function main at 0x7f18baafb2f0>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 93, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f18baafb268>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 78, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f18baafb158>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f18bab0ba58>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 46, in start
    raise e
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 35, in start
    info=self._info,
         └ <manga_py.cli.Cli object at 0x7f18bab0ba20>
  File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 35, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found
~~~

**Comment by 1271** [comment]
Oh. I read the domain incorrectly
Fixed. Will be in the next update
Thanks

**Comment by gromenauer** [comment]
Works, but still overlaps `Denma Chap 1.2` and `Denma Chap 1.2` silently.

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.1
URL | `http://heaventoon.com/denma/`

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py \
    --destination /home/manga/Manga --cbz --no-webp \
    http://heaventoon.com/denma/ \
    --simulate --print-json
~~~
~~~ json
...
  "volumes": [
    {
      "url": "http://heaventoon.com/denma-chap",
      "path": "/home/manga/Manga/denma/vol_000.cbz",
      "error": false,
      "error_message": ""
    },
    {
      "url": "http://heaventoon.com/denma-chap-1",
      "path": "/home/manga/Manga/denma/vol_001.cbz",
      "error": false,
      "error_message": ""
    },
    {
      "url": "http://heaventoon.com/denma-chap-12",
      "path": "/home/manga/Manga/denma/vol_012.cbz",
      "error": false,
      "error_message": ""
    },
...
    {
      "url": "http://heaventoon.com/denma-chap-11",
      "path": "/home/manga/Manga/denma/vol_011.cbz",
      "error": false,
      "error_message": ""
    },
    {
      "url": "http://heaventoon.com/denma-chap-12",
      "path": "/home/manga/Manga/denma/vol_012.cbz",
      "error": false,
      "error_message": ""
    },
    {
      "url": "http://heaventoon.com/denma-chap-13",
      "path": "/home/manga/Manga/denma/vol_013.cbz",
      "error": false,
      "error_message": ""
    },
...
~~~

**Comment by 1271** [comment]
I can’t fix it.
On the site, chapters 1.2 and 12 have the same address

**Comment by gromenauer** [comment]
Oops! :innocent: 
Then everything works :+1:
