### ISSUE TITLE
Feature: Add better_exceptions

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#286]
# Feature request

Add better_exceptions

~~~ py
import better_exceptions
better_exceptions.hook() # To enable it
~~~

(See https://github.com/Qix-/better-exceptions)

**Comment by gromenauer** [comment]
I see [release 18](https://github.com/manga-py/manga-py/releases/tag/1.18) out. But I'm stuck in docker and can't try it now, [docker image](https://hub.docker.com/r/mangadl/manga-py/tags) is 4 days old now (= version 1.7.1) ...

Seems that docker creation failed. See  https://github.com/manga-py/manga-py/commit/d91aca49a4461eb9c5e073e48d605904c7452da7 :
~~~
ci/dockercloud (/helpers/python/Dockerfile) — Your image failed to build in Docker Hub 
~~~

**Comment by 1271** [comment]
Oh... Sorry, you right
I fixed it today

**Comment by 1271** [comment]
@gromenauer please, check updates

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.18.1
URL | `https://manga-py.com/manga-py/` :stuck_out_tongue_winking_eye: 

~~~ bash 
run --interactive --tty --rm --name manga-py \
  -v $PWD/:/home/manga/Manga \
  mangadl/manga-py manga-py \
  --destination /home/manga/Manga \
  --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info \
  https://manga-py.com/manga-py/
~~~

~~~
"ERROR:/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py:44:2020-04-26 12:17:15,939:Please check if your inputed domain is supported by manga-py: 
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
- https://yuru-yuri.github.io/manga-py/ (deprecated)
Make sure that your inputed URL is correct
Trace:"
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │        └ <function main at 0x7fe26b9c42f0>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 93, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7fe26b9c4268>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 78, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7fe26b9c4158>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7fe26b9cba90>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 46, in start
    raise e
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 35, in start
    info=self._info,
         └ <manga_py.cli.Cli object at 0x7fe26b9cba58>
  File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 35, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found
~~~
