### ISSUE TITLE
"https://mangaseeonline.us" not working

### ISSUE THREAD

**Issue by not-lucky** [manga-py/manga-py#292]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 10
Python version | 3.7.6
Pip version | 20.0.2
Manga-py version | 1.19.2
URL | https://mangaseeonline.us/manga/Arakawa-Under-The-Bridge

#log
```
Traceback (most recent call last):
  File "c:\users\lucky\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lucky\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\Lucky\anaconda3\scripts...
         -> <code object <module> at 0x000001D01FAF46F0, file "C:\Users\Lucky\anaconda3\scripts\manga-py.exe\__main__.py", line 2>
  File "C:\Users\Lucky\anaconda3\scripts\manga-py.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |        -> <function main at 0x000001D021855558>
    -> <module 'sys' (built-in)>
  File "c:\users\lucky\anaconda3\lib\site-packages\manga_py\util.py", line 111, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x000001D021855438>
    -> <built-in function exit>
  File "c:\users\lucky\anaconda3\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x000001D021855318>
  File "c:\users\lucky\anaconda3\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x000001D02185AB08>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\lucky\anaconda3\lib\site-packages\manga_py\cli\__init__.py", line 47, in start
    self.parser.start()
    -> <manga_py.cli.Cli object at 0x000001D02185AC88>
  File "c:\users\lucky\anaconda3\lib\site-packages\manga_py\parser.py", line 44, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x000001D02185D188>
    |                     -> <manga_py.parser.Parser object at 0x000001D02185D188>
    -> <manga_py.parser.Parser object at 0x000001D02185D188>
  File "c:\users\lucky\anaconda3\lib\site-packages\manga_py\provider.py", line 91, in process
    self.chapters = self._prepare_chapters(self.get_chapters())
    |               |                      -> <manga_py.providers.mangaseeonline_us.MangaSeeOnlineUs object at 0x000001D021893388>
    |               -> <manga_py.providers.mangaseeonline_us.MangaSeeOnlineUs object at 0x000001D021893388>
    -> <manga_py.providers.mangaseeonline_us.MangaSeeOnlineUs object at 0x000001D021893388>
  File "c:\users\lucky\anaconda3\lib\site-packages\manga_py\providers\mangalife_us.py", line 33, in get_chapters
    raw_chapters = self.re.search('vm.Chapters\s*=\s*(\[\{.+\}\])'', self.content).group(1)
                   |                                                 -> <manga_py.providers.mangaseeonline_us.MangaSeeOnlineUs object at 0x000001D021893388>
                   -> <manga_py.providers.mangaseeonline_us.MangaSeeOnlineUs object at 0x000001D021893388>
AttributeError: 'NoneType' object has no attribute 'group'

```

#### Additional context
The last time I tried to download from this site, manga-py version was 1.12.2.
I tried downloading using the same version and its downloading.
But the download speed is really really slow (10 images in 2 min).

**Comment by 1271** [comment]
Unfortunately, I see that the site is very slow.
For me, opening any page lasts up to a minute now.

Check updates. This should work

Now the Internet is experiencing a high load due to the fact that many remain at home and use internet.

Take care of yourself )

**Comment by 1271** [comment]
@not-lucky Hi.
I finally found time for manga-py.
Please tell me if the problem persists?
I checked this url and everything works for me

**Comment by 1271** [comment]
Unfortunately, the site is very slow. Perhaps this is causing errors in manga-py
I just got an error in the browser.

![изображение](https://user-images.githubusercontent.com/1452243/81485007-ccd97b80-9252-11ea-8daa-9bf3a4e5bd6c.png)

**Comment by not-lucky** [comment]
Yeah, the site is working fine now in manga-py.
Thanks for the fix.

**Comment by 1271** [comment]
Thanks for using manga-py.

I am closing this issue.
If you have any questions, create a new issue.
