### ISSUE TITLE
Bug: mangakakalot.com throws AttributeError("'NoneType...) 

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#298]
# Bug report

Mangas from mangakakalot throws `[AttributeError("'NoneType' object has no attribute 'group'",)]` 

Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.3
URL | :bug: `https://mangakakalot.com/read-du5qk158504853153`
URL | :bug: `https://mangakakalot.com/read-gq1ax158504954888`
URL | :bug:  `https://mangakakalot.com/read-ne3dv158524478644`
URL | :bug:  `https://mangakakalot.com/manga/rm922554`

#### To Reproduce:
~~~ bash
docker run --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py --destination /home/manga/Manga --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
    https://mangakakalot.com/read-du5qk158504853153 -c 1
~~~

#### Additional context
Output:
~~~
[AttributeError("'NoneType' object has no attribute 'group'",)]
~~~

Output with `--debug`
~~~
"I:/manga_py/provider.py:89:2020-05-08 20:51:08,058:Manga name: du5qk158504853153"
"I:/manga_py/provider.py:90:2020-05-08 20:51:08,510:Content length 66869"
"I:/manga_py/provider.py:92:2020-05-08 20:51:08,994:Chapters received (130)"
"I:/manga_py/provider.py:100:2020-05-08 20:51:08,995:User-agent: None"
"I:/manga_py/provider.py:134:2020-05-08 20:51:08,996:Processed chapter 0 / https://mangakakalot.com/chapter/senpai_ga_urusai_kouhai_no_hanashi/chapter_1"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/helpers/manganelo_com_helper.py", line 10, in check_alternative_server
    image.raise_for_status()
    └ <Response [403]>
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
          │         │                        └ <Response [403]>
          │         └ '403 Client Error: Forbidden for url: https://s3.mkklcdnv3.com/mangakakalot/s1/senpai_ga_urusai_kouhai_no_hanashi/chapter_1/1.jp...
          └ <class 'requests.exceptions.HTTPError'>
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.mkklcdnv3.com/mangakakalot/s1/senpai_ga_urusai_kouhai_no_hanashi/chapter_1/1.jpg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │        └ <function main at 0x7f07024e1730>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 111, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f07024e1598>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f07024e1488>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f07024d3978>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7f07024d3908>
  File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 49, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7f07024d39e8>
    │                     └ <manga_py.parser.Parser object at 0x7f07024d39e8>
    └ <manga_py.parser.Parser object at 0x7f07024d39e8>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 102, in process
    self.loop_chapters()
    └ <manga_py.providers.mangakakalot_com.MangaKakalotCom object at 0x7f07024d3c18>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 138, in loop_chapters
    self._download_chapter()
    └ <manga_py.providers.mangakakalot_com.MangaKakalotCom object at 0x7f07024d3c18>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 120, in _download_chapter
    raise e
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 115, in _download_chapter
    self._storage['files'] = self.get_files()
    │                        └ <manga_py.providers.mangakakalot_com.MangaKakalotCom object at 0x7f07024d3c18>
    └ <manga_py.providers.mangakakalot_com.MangaKakalotCom object at 0x7f07024d3c18>
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/mangakakalot_com.py", line 38, in get_files
    return check_alternative_server(images, self.__alternative_cdn)
           │                        │       └ <manga_py.providers.mangakakalot_com.MangaKakalotCom object at 0x7f07024d3c18>
           │                        └ ['https://s3.mkklcdnv3.com/mangakakalot/s1/senpai_ga_urusai_kouhai_no_hanashi/chapter_1/1.jpg', 'https://s3.mkklcdnv3.com/mangak...
           └ <function check_alternative_server at 0x7f07025a51e0>
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/helpers/manganelo_com_helper.py", line 13, in check_alternative_server
    return ['%s%s' % (other_cdn, re.search(i).group(1)) for i in images]
                      │          │                               └ ['https://s3.mkklcdnv3.com/mangakakalot/s1/senpai_ga_urusai_kouhai_no_hanashi/chapter_1/1.jpg', 'https://s3.mkklcdnv3.com/mangak...
                      │          └ re.compile('^.*//[^/](/.+)$')
                      └ 'https://bu2.mkklcdnbuv1.com'
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/helpers/manganelo_com_helper.py", line 13, in <listcomp>
    return ['%s%s' % (other_cdn, re.search(i).group(1)) for i in images]
                      │          │         │                └ 'https://s3.mkklcdnv3.com/mangakakalot/s1/senpai_ga_urusai_kouhai_no_hanashi/chapter_1/1.jpg'
                      │          │         └ 'https://s3.mkklcdnv3.com/mangakakalot/s1/senpai_ga_urusai_kouhai_no_hanashi/chapter_1/1.jpg'
                      │          └ re.compile('^.*//[^/](/.+)$')
                      └ 'https://bu2.mkklcdnbuv1.com'
AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by 1271** [comment]
I temporarily removed the cdn check for mangakakalot.

Cloudflare changed security protocols. 😢 
Fixed

**Comment by gromenauer** [comment]
Works for me :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.4
URL | `https://mangakakalot.com/read-du5qk158504853153`
URL | `https://mangakakalot.com/read-gq1ax158504954888`
URL | `https://mangakakalot.com/read-ne3dv158524478644`
URL | `https://mangakakalot.com/manga/rm922554`

**Comment by gromenauer** [comment]
Maybe opening other issue for mangakakalot Cloudflare check?

**Comment by gromenauer** [comment]
OOps! this misplaced comment it's from here:
___

> 
> In #299 I put what seems the right regexp to be there. But don't always solves the problem.
> 
> I don't know how to get images form second server. 
> 
> Example where regexp works: 
> 
> Chapter: `https://mangakakalot.com/chapter/dz919342/chapter_1`
> When you click `https://mangakakalot.com/change_content_s2` images change in this way:
> ~~~
> 1: https://s5.mkklcdnv5.com/   mangakakalot/d2/dz919342/chapter_1/1.jpg
> 2: https://bu2.mkklcdnbuv1.com/mangakakalot/d2/dz919342/chapter_1/1.jpg
> ~~~
> 
> Example where regexp don't works:
> 
> Chapter: `https://mangakakalot.com/chapter/cd919002/chapter_0`
> When you click `https://mangakakalot.com/change_content_s2` images change in this way:
> ~~~
> 1: https://s41.mkklcdnv41.com/ mangakakalot/c1/cd919002           /vol1_chapter_0_metropolitan_system_prologue/1.jpg
> 2: https://bu2.mkklcdnbuv1.com/mangakakalot/m1/metropolitan_system/vol1_chapter_0_metropolitan_system_prologue/1.jpg
> ~~~

**Comment by gromenauer** [comment]
But a failed image in `https://mangakakalot.com/read-cv0il158504831406` is hard to test :/

**Comment by 1271** [comment]
>Maybe opening other issue for mangakakalot Cloudflare check?

The problem is not only for mangakakalot. All sites protected by cloudflare may be broken.

> But a failed image in https://mangakakalot.com/read-cv0il158504831406 is hard to test :/

Chapter number?

This url worked for me

**Comment by gromenauer** [comment]
`mangakakalot.com` it's working for me. 

But it warns randomly of "Chapters list empty. Check ..." today 25 of 390

Some examples:
~~~
Chapters list empty. Check https://mangakakalot.com/manga/be922724"
Chapters list empty. Check https://mangakakalot.com/manga/gu920329"
Chapters list empty. Check https://mangakakalot.com/manga/sf921440"
Chapters list empty. Check https://mangakakalot.com/read-cs2ir158504938843"
Chapters list empty. Check https://mangakakalot.com/read-pz1hs158504855881"
Chapters list empty. Check https://mangakakalot.com/read-ta2hj158504865988"
~~~

It's a schrödingBug :pouting_cat:, when you try to reproduce... it's not there. 
Reopen the bug if you can reproduce it.

**Comment by 1271** [comment]
Thank you for the clarification.
\\ I check it now

**Comment by 1271** [comment]
Ahahahah. See it
![изображение](https://user-images.githubusercontent.com/1452243/83953407-dd2c4880-a848-11ea-8a82-9d62be8308e5.png)

I will try fix it xD

**Comment by 1271** [comment]
Ahahahah. See it
![изображение](https://user-images.githubusercontent.com/1452243/83953407-dd2c4880-a848-11ea-8a82-9d62be8308e5.png)

**Comment by 1271** [comment]
This will not be fixed because it's not a mistake. Manganelo is considered a separate site, sorry
