### ISSUE TITLE
🐛 Bug: manga4life.com AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#303]
# Bug report
Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.6
URL | `https://manga4life.com/manga/Kenja-No-Mago`

#### To Reproduce:

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://manga4life.com/manga/Kenja-No-Mago \
    -c 3
~~~

#### Additional context

~~~
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │        └ <function main at 0x7fbc5957dae8>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 110, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7fbc5957d950>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7fbc5957d840>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7fbc58e2ba90>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7fbc58e2ba58>
  File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 59, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7fbc58e2ba20>
    │                     └ <manga_py.parser.Parser object at 0x7fbc58e2ba20>
    └ <manga_py.parser.Parser object at 0x7fbc58e2ba20>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 105, in process
    self.loop_chapters()
    └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7fbc58e2bd30>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 133, in loop_chapters
    if idx < _min or (count >= _max > 0) or self._check_archive():
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 109, in _check_archive
    _path = '%s.%s' % self.get_archive_path()
                      └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7fbc58e2bd30>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 191, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
            │                        └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7fbc58e2bd30>
            └ <function remove_file_query_params at 0x7fbc594460d0>
  File "/usr/local/lib/python3.6/site-packages/manga_py/base_classes/arc_name.py", line 12, in get_archive_name
    idx = self.get_chapter_index()
          └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7fbc58e2bd30>
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/mangalife_us.py", line 14, in get_chapter_index
    chapter = self.re.search(selector, self.chapter).group(1).split('.')
    │         │              │         └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7fbc58e2bd30>
    │         │              └ '-chapter-(\\d+(?:\\.\\d+)?)'
    │         └ <manga_py.providers.mangalife_us.MangaLifeUs object at 0x7fbc58e2bd30>
    └ None
AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by 1271** [comment]
Thank you so much. You do a lot for manga-py.

**Comment by gromenauer** [comment]
I'm a happy user (who complains a lot :)

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.7
URL | `https://manga4life.com/manga/Kenja-No-Mago`
