### ISSUE TITLE
🐛 Bug: webtoons.com age redirection

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#304]
# Bug report

Got stuck with age redirection.

Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.7
URL | `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88`
          
#### To Reproduce:

~~~ bash
docker run --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    'https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88' \
    -c3
~~~

#### Additional context

Output: 

~~~
"WARNING:/manga_py/parser.py:43:2020-05-23 15:29:28,456:Manga url changed! New url: https://www.webtoons.com/en/ageGate"
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │        └ <function main at 0x7f1bcbf18b70>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 110, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f1bcbf189d8>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f1bcbf188c8>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f1bcbf15a90>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7f1bcbf15a58>
  File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 59, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7f1bcbf15a20>
    │                     └ <manga_py.parser.Parser object at 0x7f1bcbf15a20>
    └ <manga_py.parser.Parser object at 0x7f1bcbf15a20>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 89, in process
    info('Manga name: %s' % self.manga_name)
    │                       └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f1bcbf15e48>
    └ <function info at 0x7f1bcc8b81e0>
  File "/usr/local/lib/python3.6/site-packages/manga_py/base_classes/params.py", line 17, in manga_name
    name = self.get_manga_name()
    │      └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f1bcbf15e48>
    └ None
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/webtoons_com.py", line 24, in get_manga_name
    self.__titleNo = self._get_name('title_no=(\d+)'')
    │                └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f1bcbf15e48>
    └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f1bcbf15e48>
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/helpers/std.py", line 56, in _get_name
    return re.search(selector, url).group(1)
           │         │         └ 'https://www.webtoons.com/en/ageGate'
           │         └ 'title_no=(\\d+)'
           └ <module 're' from '/usr/local/lib/python3.6/re.py'>
AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by 1271** [comment]
Can you tell me which cookies are required to confirm age? (It's worked ok for me)

**Comment by gromenauer** [comment]
I think ageGatePass and needGDPR are the two for me
<details>

 <summary>When I erased all cookies and just login. This were the cookies in my browser: </summary>
 <p>

~~~ json
[{
	"Host raw": "http://.webtoons.com/",
	"Name raw": "ageGatePass",
	"Path raw": "/",
	"Content raw": "true",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
},
{
	"Host raw": "http://.webtoons.com/",
	"Name raw": "needGDPR",
	"Path raw": "/",
	"Content raw": "true",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
},
{
	"Host raw": "http://.webtoons.com/",
	"Name raw": "locale",
	"Path raw": "/",
	"Content raw": "en",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
},
{
	"Host raw": "http://.webtoons.com/",
	"Name raw": "wtv",
	"Path raw": "/",
	"Content raw": "1",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
},
{
	"Host raw": "http://.webtoons.com/",
	"Name raw": "timezoneOffset",
	"Path raw": "/",
	"Content raw": "+2",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
},
{
	"Host raw": "http://.webtoons.com/",
	"Name raw": "wtu",
	"Path raw": "/",
	"Content raw": "\"QWERTYUIOPASDFGHJLZXCVBNMQW\"",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
},
{
	"Host raw": "http://.webtoons.com/",
	"Name raw": "wts",
	"Path raw": "/",
	"Content raw": "1234567890123",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Any type of connection",
	"Send for raw": "false",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
},
{
	"Host raw": "https://.loginfra.com/",
	"Name raw": "NNB",
	"Path raw": "/",
	"Content raw": "QWERTYUIOPASD",
	"Expires": "At the end of the session",
	"Expires raw": "0",
	"Send for": "Encrypted connections only",
	"Send for raw": "true",
	"HTTP only raw": "false",
	"SameSite raw": "no_restriction",
	"This domain only": "Valid for subdomains",
	"This domain only raw": "false",
	"Store raw": "firefox-default",
	"First Party Domain": ""
}]
~~~

  </p>
</details>

**Comment by gromenauer** [comment]
Tried without luck :thinking: :

~~~ bash
docker run  -u 0:0 --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py /bin/bash
pip install --upgrade pip pyvim
pyvim /usr/local/lib/python3.6/site-packages/manga_py/providers/webtoons_com.py
~~~

~~~ py
    def prepare_cookies(self):
        self.http().cookies['ageGatePass'] = 'true'
        self.http().cookies['needGDPR'] = 'true'
        self.http().referer = 'https://www.webtoons.com/en/'
~~~

~~~ bash
manga-py https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88
"WARNING:/manga_py/parser.py:43:2020-05-24 11:51:48,121:Manga url changed! New url: https://www.webtoons.com/en/ageGate"
...
AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by gromenauer** [comment]
Tried a bit more, but nothing:

~~~ py
    def prepare_cookies(self):
        self.http().cookies['ageGatePass'] = 'true'
        self.http().cookies['needGDPR'] = 'true'
        self.http().cookies['locale'] = 'en'
        self.http().cookies['wtv'] = '1'
        self.http().cookies['timezoneOffset'] = '+2'
        self.http().referer = 'https://www.webtoons.com/en/ageGate'
~~~

**Comment by 1271** [comment]
Ок. I'll try again in the evening :smile:

**Comment by 1271** [comment]
> Tried a bit more, but nothing:

And if so?

` self.http().cookies['needGDPR'] = 'false' `


This cookies is for me (but they don’t show me the age confirmation page):

![изображение](https://user-images.githubusercontent.com/1452243/83118376-f3af0300-a0d6-11ea-964c-fd523c2aa43a.png)/

**Comment by 1271** [comment]
I did it! (country Italy)

**Comment by 1271** [comment]
Please, try from git, if you can.
It seems to work again

**Comment by gromenauer** [comment]
Same error :/

Used docker container as in comment https://github.com/manga-py/manga-py/issues/305#issuecomment-635496119
~~~ py
"WARNING:/manga_py/parser.py:43:2020-05-28 17:44:44,620:Manga url changed! New url: https://www.webtoons.com/en/ageGate"
Traceback (most recent call last):
  File "./manga.py", line 8, in <module>
    main()
    └ <function main at 0x7f23a8737048>
  File "/root/manga-py/manga_py/util.py", line 110, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f23a8736e18>
    └ <built-in function exit>
  File "/root/manga-py/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f23a8736d08>
  File "/root/manga-py/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f23a873f2b0>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/root/manga-py/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7f23a873f358>
  File "/root/manga-py/manga_py/parser.py", line 59, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7f23a873f400>
    │                     └ <manga_py.parser.Parser object at 0x7f23a873f400>
    └ <manga_py.parser.Parser object at 0x7f23a873f400>
  File "/root/manga-py/manga_py/provider.py", line 89, in process
    info('Manga name: %s' % self.manga_name)
    │                       └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f23a873f4a8>
    └ <function info at 0x7f23aa4d8f28>
  File "/root/manga-py/manga_py/base_classes/params.py", line 17, in manga_name
    name = self.get_manga_name()
    │      └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f23a873f4a8>
    └ None
  File "/root/manga-py/manga_py/providers/webtoons_com.py", line 24, in get_manga_name
    self.__titleNo = self._get_name('title_no=(\d+)'')
    │                └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f23a873f4a8>
    └ <manga_py.providers.webtoons_com.WebToonsCom object at 0x7f23a873f4a8>
  File "/root/manga-py/manga_py/providers/helpers/std.py", line 56, in _get_name
    return re.search(selector, url).group(1)
           │         │         └ 'https://www.webtoons.com/en/ageGate'
           │         └ 'title_no=(\\d+)'
           └ <module 're' from '/usr/lib/python3.7/re.py'>
AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by gromenauer** [comment]
Any chance to manga-py visit `https://www.webtoons.com/en/ageGate`, fill the form and get the personalized cookies?

**Comment by 1271** [comment]
The form sets nothing except 'ageGatePass' = 'true'

**Comment by 1271** [comment]
Oh. Maybe I understand what the problem is.
I'll try to fix it

**Comment by 1271** [comment]
Please, check new version

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.8
URL | `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88`
