### ISSUE TITLE
➕ Request to add: read.ptscans.com

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#305]
# Request to add a site

Description | Data
---|---
Url to add |`https://read.ptscans.com/series/exterminator/`

**Comment by 1271** [comment]
Please, try from git, if you can.
It seems to work

**Comment by gromenauer** [comment]
No luck :shrug: 

~~~ bash
# Can't use manga-py docker image to test this (no git inside).
docker run --interactive --tty --rm --name manga-py-dev debian:buster-slim /bin/bash
apt update
apt install -y python3 python3-pip git
python3 -m pip install --user --upgrade pip
PATH=/root/.local/bin:$PATH

# python3 -m pip install --user --upgrade pip git+https://github.com/manga-py/manga-py.git@stable_1.x
# python3 -m pip install --user --upgrade pip https://github.com/manga-py/manga-py/archive/stable_1.x.zip
# 🤔 !?

cd
git clone https://github.com/manga-py/manga-py.git
cd manga-py
python3 -m pip install --user --upgrade --requirement requirements.txt
python3 ./manga.py https://read.ptscans.com/series/exterminator/
# 💥
~~~
Error:
~~~ py
Traceback (most recent call last):
  File "./manga.py", line 8, in <module>
    main()
    └ <function main at 0x7f2415954048>
  File "/root/manga-py/manga_py/util.py", line 110, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f2415953e18>
    └ <built-in function exit>
  File "/root/manga-py/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f2415953d08>
  File "/root/manga-py/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f241595c160>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/root/manga-py/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7f241595c198>
  File "/root/manga-py/manga_py/parser.py", line 59, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7f241595c2e8>
    │                     └ <manga_py.parser.Parser object at 0x7f241595c2e8>
    └ <manga_py.parser.Parser object at 0x7f241595c2e8>
  File "/root/manga-py/manga_py/provider.py", line 105, in process
    self.loop_chapters()
    └ <manga_py.providers.read_ptscans_com.ReadPtscansCom object at 0x7f241595c6a0>
  File "/root/manga-py/manga_py/provider.py", line 133, in loop_chapters
    if idx < _min or (count >= _max > 0) or self._check_archive():
  File "/root/manga-py/manga_py/provider.py", line 109, in _check_archive
    _path = '%s.%s' % self.get_archive_path()
                      └ <manga_py.providers.read_ptscans_com.ReadPtscansCom object at 0x7f241595c6a0>
  File "/root/manga-py/manga_py/provider.py", line 191, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
            │                        └ <manga_py.providers.read_ptscans_com.ReadPtscansCom object at 0x7f241595c6a0>
            └ <function remove_file_query_params at 0x7f24175e9d90>
  File "/root/manga-py/manga_py/base_classes/arc_name.py", line 12, in get_archive_name
    idx = self.get_chapter_index()
          └ <manga_py.providers.read_ptscans_com.ReadPtscansCom object at 0x7f241595c6a0>
  File "/root/manga-py/manga_py/providers/read_ptscans_com.py", line 8, in get_chapter_index
    return self.re.search('.+?(\d+(?:\.\d+))\s*$'', chapter)\
           │                                        └ 'Chapter 18'
           └ <manga_py.providers.read_ptscans_com.ReadPtscansCom object at 0x7f241595c6a0>
AttributeError: 'NoneType' object has no attribute 'group'
~~~

**Comment by 1271** [comment]
Hmm... then I need a little more time

**Comment by 1271** [comment]
Please, check new version

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.8
URL | `https://read.ptscans.com/series/exterminator/`
