### ISSUE TITLE
Jamini's Box

### ISSUE THREAD

**Issue by XantherBanter** [manga-py/manga-py#312]
# Request to add a site

Description | Data
---|---
Url to add | https://jaiminisbox.com/

**Comment by 1271** [comment]
@XantherBanter
 If you have no problems using, I will close issue.
Could you check updates?

**Comment by XantherBanter** [comment]
Don't see any updates for jamini's @1271

**Comment by 1271** [comment]
@XantherBanter manga-py version?

v1.19.12:
https://github.com/manga-py/manga-py/blob/7924c37a89ee92a4012347c94b116b09d57943e4/manga_py/providers/__init__.py#L97-L99

**Comment by XantherBanter** [comment]
Same version. Tried one. Here's the command used and the traceback.

Ubuntu 18.04 LTS, Python 3.6.9, pip 9.0.3. Used pipx 0.15.4.0 to install `manga-py`
```
manga-py https://jaiminisbox.com/reader/series/fire-force
Traceback (most recent call last):
  File "/home/xan/.local/bin/manga-py", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x7facc2efb0d0>
    └ <module 'sys' (built-in)>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/util.py", line 111, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7facc2ef8ea0>
    └ <built-in function exit>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7facc2ef8d90>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7facc2f040f0>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7facc2f04080>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7facc2f04160>
    │                     └ <manga_py.parser.Parser object at 0x7facc2f04160>
    └ <manga_py.parser.Parser object at 0x7facc2f04160>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/provider.py", line 89, in process
    info('Manga name: %s' % self.manga_name)
    │                       └ <manga_py.providers.gomanga_co.GoMangaCo object at 0x7facc2f04198>
    └ <function info at 0x7facc5b8b8c8>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/base_classes/params.py", line 17, in manga_name
    name = self.get_manga_name()
    │      └ <manga_py.providers.gomanga_co.GoMangaCo object at 0x7facc2f04198>
    └ None
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/providers/gomanga_co.py", line 21, in get_manga_name
    return self._get_name(self._name_re)
           │              └ <manga_py.providers.gomanga_co.GoMangaCo object at 0x7facc2f04198>
           └ <manga_py.providers.gomanga_co.GoMangaCo object at 0x7facc2f04198>
  File "/home/xan/.local/pipx/venvs/manga-py/lib/python3.6/site-packages/manga_py/providers/helpers/std.py", line 59, in _get_name
    return re.search(selector, url).group(1)
           │         │         └ 'https://jaiminisbox.com/reader/series/fire-force'
           │         └ '/reader/[^/]+/([^/]+)/'
           └ <module 're' from '/usr/lib/python3.6/re.py'>
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by 1271** [comment]
Hmm .. I'll check it out a bit later.
thanks

**Comment by gromenauer** [comment]
Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.12
URL | `https://jaiminisbox.com/reader/series/fire-force/`
          
~~~ bash
docker run \
  --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py \
    --destination /home/manga/Manga --cbz --zero-fill --rename-pages \
    --no-webp --show-current-chapter-info \
    https://jaiminisbox.com/reader/series/fire-force/ \
    -c 3

[AttributeError("'NoneType' object has no attribute 'group'",)]
[AttributeError("'NoneType' object has no attribute 'group'",)]
[AttributeError("'NoneType' object has no attribute 'group'",)]
~~~

**Comment by 1271** [comment]
Please, check updates. It should work now


P.S.
Maybe, last time, I was lucky and I got the page without confusion? I dont know

**Comment by XantherBanter** [comment]
@1271 works now. Cheers.

**Comment by gromenauer** [comment]
Works for me too :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.5
Manga-py version | 1.19.13
URL | `https://jaiminisbox.com/reader/series/fire-force/`
