### ISSUE TITLE
🐛 Bug: mangawindow.net IndexError

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#315]
# Bug report

Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.4
Manga-py version | 1.19.12
URL | `https://mangawindow.net/series/69693`
  

#### To Reproduce:

~~~ bash
docker run \
  --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py \
    --destination /home/manga/Manga --cbz --zero-fill --rename-pages \
    --no-webp --show-current-chapter-info \
    https://mangawindow.net/series/69693
~~~

#### Additional context

Output:

~~~ py
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 10, in <module>
    sys.exit(main())
    │        └ <function main at 0x7ff509c159d8>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 111, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7ff509c15840>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7ff509c15730>
  File "/usr/local/lib/python3.6/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7ff509c13390>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7ff509c13358>
  File "/usr/local/lib/python3.6/site-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7ff509c133c8>
    │                     └ <manga_py.parser.Parser object at 0x7ff509c133c8>
    └ <manga_py.parser.Parser object at 0x7ff509c133c8>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 89, in process
    info('Manga name: %s' % self.manga_name)
    │                       └ <manga_py.providers.mangawindow_net.MangaWindowNet object at 0x7ff509c135c0>
    └ <function info at 0x7ff509fd91e0>
  File "/usr/local/lib/python3.6/site-packages/manga_py/base_classes/params.py", line 17, in manga_name
    name = self.get_manga_name()
    │      └ <manga_py.providers.mangawindow_net.MangaWindowNet object at 0x7ff509c135c0>
    └ None
  File "/usr/local/lib/python3.6/site-packages/manga_py/providers/mangawindow_net.py", line 15, in get_manga_name
    title = self.html_fromstring(self.get_url(), '.item-title > a, .nav-title > a', 0)
            │                    └ <manga_py.providers.mangawindow_net.MangaWindowNet object at 0x7ff509c135c0>
            └ <manga_py.providers.mangawindow_net.MangaWindowNet object at 0x7ff509c135c0>
  File "/usr/local/lib/python3.6/site-packages/manga_py/provider.py", line 244, in html_fromstring
    return self.document_fromstring(self.http_get(url, **params), selector, idx)
           │                        │             │      │        │         └ 0
           │                        │             │      │        └ '.item-title > a, .nav-title > a'
           │                        │             │      └ {}
           │                        │             └ 'https://mangawindow.net/series/69693'
           │                        └ <manga_py.providers.mangawindow_net.MangaWindowNet object at 0x7ff509c135c0>
           └ <manga_py.providers.mangawindow_net.MangaWindowNet object at 0x7ff509c135c0>
  File "/usr/local/lib/python3.6/site-packages/manga_py/base_classes/static.py", line 24, in document_fromstring
    result = result[idx]
    │        │      └ 0
    │        └ []
    └ []
IndexError: list index out of range
~~~

**Comment by 1271** [comment]
They got cloudflare protection. Fixed :+1:

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Debian GNU/Linux 10 (buster)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.14.5
Manga-py version | 1.19.13
URL | `https://mangawindow.net/series/69693`
