### ISSUE TITLE
cloudflare package asking for money

### ISSUE THREAD

**Issue by phanirithvij** [manga-py/manga-py#322]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 10
Python version | 3.8.0
Pip version | 20.1.1
Manga-py version | 1.19.13
URL | https://readcomiconline.to/Comic/The-New-52-Futures-End

#### To Reproduce:
1. `manga-py.exe "https://readcomiconline.to/Comic/The-New-52-Futures-End"`
The error is
```py
"ERROR:\cloudscraper\__init__.py:776:2020-07-25 16:41:12,041:"https://readcomiconline.to/Comic/The-New-52-Futures-End" returned an error. Could not collect tokens."
"ERROR:\manga_py\base_classes\cf_protect.py:28:2020-07-25 16:41:12,043:Detected a Cloudflare version 2 challenge, Paid version required to solve."
```

Full error

<details>
<summary> Expand </summary>

```py
"ERROR:\cloudscraper\__init__.py:776:2020-07-25 16:41:12,041:"https://readcomiconline.to/Comic/The-New-52-Futures-End" returned an error. Could not collect tokens."
"ERROR:\manga_py\base_classes\cf_protect.py:28:2020-07-25 16:41:12,043:Detected a Cloudflare version 2 challenge, Paid version required to solve."
Traceback (most recent call last):
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\Rithvij\AppData\Local\P...
         -> <code object <module> at 0x000002568E3092F0, file "C:\Users\Rithvij\AppData\Local\Programs\Python\Python38\Scripts\manga-py.exe\...
  File "C:\Users\Rithvij\AppData\Local\Programs\Python\Python38\Scripts\manga-py.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |        -> <function main at 0x000002568F5D23A0>
    -> <module 'sys' (built-in)>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 111, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x000002568F5D20D0>
    -> <built-in function exit>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x000002568F5D0F70>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x000002568F5CCEB0>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 47, in start

    self.parser.start()
    -> <manga_py.cli.Cli object at 0x000002568F5CCA00>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x000002568F5CCBE0>
    |                     -> <manga_py.parser.Parser object at 0x000002568F5CCBE0>
    -> <manga_py.parser.Parser object at 0x000002568F5CCBE0>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\provider.py", line 87, in process
    self.prepare_cookies()
    -> <manga_py.providers.readcomiconline_to.ReadComicOnlineTo object at 0x000002568E7DBEE0>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\providers\readcomiconline_to.py", line 23, in prepare_cookies
    self.cf_scrape(self.get_url())
    |              -> <manga_py.providers.readcomiconline_to.ReadComicOnlineTo object at 0x000002568E7DBEE0>
    -> <manga_py.providers.readcomiconline_to.ReadComicOnlineTo object at 0x000002568E7DBEE0>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\provider.py", line 267, in cf_scrape
    params = cf_scrape(url)
             |         -> 'https://readcomiconline.to/Comic/The-New-52-Futures-End'
             -> <function cf_scrape at 0x000002568F4E4040>
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\base_classes\cf_protect.py", line 29, in cf_scrape
    raise e
  File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\manga_py\base_classes\cf_protect.py", line 22, in cf_scrape
    cookies, ua = scraper.get_tokens(url)
                  |                  -> 'https://readcomiconline.to/Comic/The-New-52-Futures-End'
                  -> <cloudscraper.CloudScraper object at 0x000002568F5CCCD0>
```

</details>

#### Additional context

I remember the Cloudflare package being https://github.com/Anorov/cloudflare-scrape/  but it was changed to this https://github.com/VeNoMouS/cloudscraper?

**Comment by phanirithvij** [comment]
I see that the cloud scraper dude is starting a business on github sacrificing his face to look like an ass.
And the CEO of Cloudflare is enjoying it https://twitter.com/eastdakota/status/1273277839102656515 also looking like an ass. 

And Anorov is out fishing and most likely doesn't know about this.

**Comment by 1271** [comment]
I will try to find an alternative solution.
Thanks for the issue

P.S. 
`anorov/cloudflare-scrape` does not support the project since march

**Comment by 1271** [comment]
Upd:
Currently, any issue regarding cloudflare will be dismissed until someone in the python / javascript community makes something new.

**Comment by 1271** [comment]
An alternative way to bypass cloudflare protection is to pass user-agent and cf_clearance cookies to manga-py.

Example:

```bash
manga-py https://bato.to/series/78510 --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"  --cookies cf_clearance=9ced1dc4068fb9ecf00ef41836eec5e6ea4779b8-1595750924-0-1z876a9225zbb5514c6z30f2590-150 __cfduid=d70b43850ffa05c7a57b7856e15af43de1595750935
```

**Comment by phanirithvij** [comment]
@1271 I tried it after updating to 1.19.14 it's working. I wrote a simple selenium script to get the cfid cookies.

It opens the browser and we need to solve the captcha and after captcha is solved it will close. **OF COURSE, IT IS NOT AUTOMATED** 

```py
import json

from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait


def setup_driver():
    options = webdriver.ChromeOptions()
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option('useAutomationExtension', False)

    # specific to my pc
    options.binary_location = "C:\Program Files (x86)\Google\Chrome Beta\Application\chrome.exe"
    driver = webdriver.Chrome(
        options=options,
        executable_path="D:\Projects\BrowserStack\grid_ui\chromedriver_win32\chromedriver.exe"
    )
    return driver


driver = setup_driver()

driver.get("https://readcomiconline.to/")


def captcha_solved(*args):
    title = driver.execute_script("return document.title")
    if title in ["Just a moment...", "Attention Required! | Cloudflare"]:
        return False
    else:
        # if title is not a cloudflare thing we solved the captcha
        return True


try:
    element = WebDriverWait(driver, 200).until(captcha_solved)
finally:
    with open("cookies.json", 'w+') as cookies:
        json.dump({
            'cookies': driver.get_cookies(),
            'ua': driver.execute_script("return navigator.userAgent")
        },
            cookies
        )
    driver.quit()

```

It will save cookies to a json file

Then use this to read the cookies from the file to run the download

```py
import subprocess
import json

user_agent = '--user-agent '
url = '"https://readcomiconline.to/Comic/The-New-52-Futures-End"'

cookies = "--cookies "
required_cookies = ['cf_chl_1', 'cf_clearance', '__cfduid']

with open('cookies.json', 'r') as cookies_file:
    allc = json.load(cookies_file)
    for k in allc['cookies']:
        if k['name'] in required_cookies:
            cookies += f"{k['name']}={k['value']} "
    user_agent += f"""\"{allc['ua']}\""""

if __name__ == "__main__":
    print(f'manga-py {url} {user_agent} {cookies}')
    subprocess.call(f'manga-py {url} {user_agent} {cookies}', shell=True)

```

**Comment by 1271** [comment]
selenium bypasses these restrictions, that's right. But this will not work on some devices + will add the obligation to install the browser.
You can use selenium to receive cookies and pass them to manga-py
It's very easy to automate. You can also store cookies so that you don't receive them every time.
