### ISSUE TITLE
Docker: ImportError: cannot import name 'UnidentifiedImageError'

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#326]
# Bug report
Environment :

docker last version

#### To Reproduce:
1. clean docker
~~~ sh
docker rm $(docker ps -aq)
docker image rm $(docker image ls -aq)
~~~
1. Launch manga-py in docker:
~~~ sh
docker run mangadl/manga-py manga-py --version
~~~

#### Additional context
Output
~~~
Unable to find image 'mangadl/manga-py:latest' locally
latest: Pulling from mangadl/manga-py
7595c8c21622: Pull complete 
d13af8ca898f: Pull complete 
70799171ddba: Pull complete 
b6c12202c5ef: Pull complete 
cbc98f4502ae: Pull complete 
e44263ae6388: Pull complete 
9d17bdfd6117: Pull complete 
b1932e2728e9: Pull complete 
02dd833b1f29: Pull complete 
dc2454f61035: Pull complete 
42a61715ace4: Pull complete 
5dbc40bab1b4: Pull complete 
ac5a48735818: Pull complete 
Digest: sha256:ae8184a4700a85254be3f97930c8720e0ed4bbd65f5e0083e0aee900c16132c1
Status: Downloaded newer image for mangadl/manga-py:latest
~~~
Error
~~~ py
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.20', 'console_scripts', 'manga-py')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 10, in <module>
    from manga_py.parser import Parser
  File "/usr/local/lib/python3.6/dist-packages/manga_py/parser.py", line 5, in <module>
    from .provider import Provider
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 8, in <module>
    from .base_classes import (
  File "/usr/local/lib/python3.6/dist-packages/manga_py/base_classes/__init__.py", line 2, in <module>
    from .archive import Archive
  File "/usr/local/lib/python3.6/dist-packages/manga_py/base_classes/archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "/usr/local/lib/python3.6/dist-packages/manga_py/manga_image.py", line 6, in <module>
    from PIL import Image as PilImage, ImageChops, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError'
~~~

**Comment by 1271** [comment]
Oh ... thanks for the issue
I haven't checked it, sorry

**Comment by gromenauer** [comment]
Works... with a quirk 

Version :heavy_check_mark: 
~~~ sh
docker run mangadl/manga-py manga-py --version
1.20.1
~~~

Same example as #298 :x: 
~~~ sh
docker run --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py \
  manga-py --destination /home/manga/Manga --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
    https://mangakakalot.com/read-du5qk158504853153 -c 1
~~~ 
~~~
usage: manga-py [-v] [-n NAME] [-d PATH] [-P] [--arguments [str [str ...]]] [-s COUNT] [-c COUNT]
                [-u str] [--cookies [str [str ...]]] [-x str] [-r] [-w] [-t int] [-f] [-p URL] [-N]
                [-o ARCHIVE_NAME] [-S MB] [-z] [-R] [-E] [-W] [-h] [--print-json] [--simulate]
                [--show-current-chapter-info] [--debug] [-q]
                URL
manga-py: error: unrecognized arguments: https://mangakakalot.com/read-du5qk158504853153
~~~

Without manga-py invocation :heavy_check_mark: 
~~~ sh
docker run --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga mangadl/manga-py \
   --destination /home/manga/Manga --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
    https://mangakakalot.com/read-du5qk158504853153 -c 1
~~~ 
~~~
Current chapter url: https://mangakakalot.com/chapter/senpai_ga_urusai_kouhai_no_hanashi/chapter_1

100% (4 of 4) |###############################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
~~~

**Comment by 1271** [comment]
Right. I forgot to indicate. Dockerfile now contains entrypoint and does not require duplicate manga-py call
See:
https://github.com/manga-py/manga-py/blob/c2e674ad700411114879965a874f4a30f305142c/Dockerfile#L61-L63

**Comment by 1271** [comment]
And it calls are identical:

`docker run mangadl/manga-py manga-py --version` == `docker run mangadl/manga-py`

**Comment by gromenauer** [comment]
OK to me :+1:

**Comment by gromenauer** [comment]
A convoluted way to say the same: 
~~~ bash
docker run --entrypoint manga-py mangadl/manga-py --version
~~~
(to get scripts almost unchanged)

**Comment by 1271** [comment]
Yeah, true 👍
