### ISSUE TITLE
[BUG] mangasushi.net Chapters list empty

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#330]
# Bug report
Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.20.3
URL | `https://mangasushi.net/manga/yondome-wa-iyana-shi-zokusei-majutsushi/`

#### To Reproduce:

``` sh
docker run \
  --interactive --tty --rm --name manga-py -v $PWD:/home/manga/Manga --entrypoint manga-py \
  mangadl/manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://mangasushi.net/manga/yondome-wa-iyana-shi-zokusei-majutsushi/
```

#### Additional context

Output
```
"WARNING:/manga_py/base_classes/base.py:103:2020-08-15 12:05:53,699:Chapters list empty. Check https://mangasushi.net/manga/yondome-wa-iyana-shi-zokusei-majutsushi/"
No new chapters found
```

___
Additional note. Seems to use `madara` theme: https://themeforest.net/item/madara-wordpress-theme-for-manga/20849828
Take a look at `https://docs.google.com/spreadsheets/d/1TyJEUg78WWH4zgnf3g6M2lkbWpBWbd40FYiPVQhW8IU/edit#gid=0&range=C143` for similars webs to try to add.

Tried `manga-py https://www.mangalord.com/manga/im-an-overlord/ --force-provider https://mangasushi.net/manga/yondome-wa-iyana-shi-zokusei-majutsushi/` and it works.

**Comment by 1271** [comment]
thanks for the issue

**Comment by gromenauer** [comment]
Please add `asurascans.com` too.
Tried `manga-py https://asurascans.com/manga/omniscient-readers-viewpoint/ --force-provider https://mangasushi.net/manga/yondome-wa-iyana-shi-zokusei-majutsushi/` and seems that will work when `Chapters list empty` is fixed.

**Comment by gromenauer** [comment]
Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.21
URL | `https://mangasushi.net/manga/yondome-wa-iyana-shi-zokusei-majutsushi/`


``` py
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.21', 'console_scripts', 'manga-py')()
    └ <function load_entry_point at 0x7fd1f4d089d8>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7fd1ef2da840>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7fd1ef2da730>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7fd1ef2e0a90>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7fd1ef2e0a58>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7fd1ef2e0ac8>
    │                     └ <manga_py.parser.Parser object at 0x7fd1ef2e0ac8>
    └ <manga_py.parser.Parser object at 0x7fd1ef2e0ac8>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 97, in process
    self.chapters = self._prepare_chapters(self.get_chapters())
    │               │                      └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7fd1ef2e0b00>
    │               └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7fd1ef2e0b00>
    └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7fd1ef2e0b00>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/providers/rawdevart_com_old.py", line 28, in get_chapters
    items = self._elements('.wp-manga-chapter > a', items_content)
    │       │                                       └ <Response [200]>
    │       └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7fd1ef2e0b00>
    └ []
  File "/usr/local/lib/python3.6/dist-packages/manga_py/providers/helpers/std.py", line 15, in _elements
    return self.document_fromstring(content, selector)
           │                        │        └ '.wp-manga-chapter > a'
           │                        └ <Response [200]>
           └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7fd1ef2e0b00>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/base_classes/static.py", line 20, in document_fromstring
    result = document_fromstring(body)  # todo
             │                   └ <Response [200]>
             └ <function document_fromstring at 0x7fd1f016e400>
  File "/usr/lib/python3/dist-packages/lxml/html/__init__.py", line 762, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
            │                │     │         └ {}
            │                │     └ <lxml.html.HTMLParser object at 0x7fd1f0179eb8>
            │                └ <Response [200]>
            └ <module 'lxml.etree' from '/usr/lib/python3/dist-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so'>
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseMemoryDocument
```

**Comment by 1271** [comment]
Oh, this is my fault.
I'll fix it today. thanks

**Comment by gromenauer** [comment]
Seems that the error have changed (?)

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.21
URL | `https://asurascans.com/manga/a-returners-magic-should-be-special/`
          
``` sh
docker run \
  --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga --entrypoint manga-py \
  mangadl/manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://asurascans.com/manga/a-returners-magic-should-be-special/
```

``` py
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.21', 'console_scripts', 'manga-py')()
    └ <function load_entry_point at 0x7f6ce21a89d8>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f6cdc77a840>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f6cdc77a730>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f6cdc77cac8>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7f6cdc77ca90>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7f6cdc77cb00>
    │                     └ <manga_py.parser.Parser object at 0x7f6cdc77cb00>
    └ <manga_py.parser.Parser object at 0x7f6cdc77cb00>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 97, in process
    self.chapters = self._prepare_chapters(self.get_chapters())
    │               │                      └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7f6cdc77cb38>
    │               └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7f6cdc77cb38>
    └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7f6cdc77cb38>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/providers/rawdevart_com_old.py", line 23, in get_chapters
    manga_id = self._elements('#manga-chapters-holder')[0].get('data-id')
               └ <manga_py.providers.mangasushi_net.MangaSushiNet object at 0x7f6cdc77cb38>
IndexError: list index out of range
```

**Comment by 1271** [comment]
Sorry to wait. Unfortunately, now I have some problems in my family. I will definitely come back as soon as I solve some of them.
Thank you for understanding

**Comment by gromenauer** [comment]
Avoid burnout, mental health comes first.
(And don't worry, no manga will be deleted from the servers)

**Comment by 1271** [comment]
Fixed together with #332

**Comment by gromenauer** [comment]
Thanks for the fix! :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.22
URL | `https://mangasushi.net/manga/yondome-wa-iyana-shi-zokusei-majutsushi/`

**Comment by 1271** [comment]
@gromenauer  Thanks for the constant checks and bug notifications. 
![изображение](https://user-images.githubusercontent.com/1452243/95012314-3f9f2500-0640-11eb-8c20-76951c2294a6.png)
