### ISSUE TITLE
[BUG] isekaiscan.com Chapters list empty

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#332]
# Bug report

#### Environment:

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.4 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.20.3
URL | `https://isekaiscan.com/manga/the-ultimate-middle-aged-hunter-travels-to-another-world-this-time-he-wants-to-live-a-slow-and-peaceful-life/`

#### To Reproduce:

``` bash
docker run \
  --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga --entrypoint manga-py \
  mangadl/manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://isekaiscan.com/manga/the-ultimate-middle-aged-hunter-travels-to-another-world-this-time-he-wants-to-live-a-slow-and-peaceful-life/
```

#### Additional context

More than 11 chapters are in the web but none is detected.

```
"WARNING:/manga_py/base_classes/base.py:103:2020-08-29 12:15:21,045:Chapters list empty. Check https://isekaiscan.com/manga/the-ultimate-middle-aged-hunter-travels-to-another-world-this-time-he-wants-to-live-a-slow-and-peaceful-life/"
No new chapters found
```

**Comment by 1271** [comment]
Thanks for the issue, I'll check it tomorrow.

**Comment by gromenauer** [comment]
Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.21
URL | `https://isekaiscan.com/manga/the-ultimate-middle-aged-hunter-travels-to-another-world-this-time-he-wants-to-live-a-slow-and-peaceful-life/`

``` py
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.21', 'console_scripts', 'manga-py')()
    └ <function load_entry_point at 0x7f6f508719d8>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f6f4ae42840>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f6f4ae42730>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f6f4ae44ac8>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7f6f4ae44a90>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7f6f4ae44b00>
    │                     └ <manga_py.parser.Parser object at 0x7f6f4ae44b00>
    └ <manga_py.parser.Parser object at 0x7f6f4ae44b00>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 97, in process
    self.chapters = self._prepare_chapters(self.get_chapters())
    │               │                      └ <manga_py.providers.isekaiscan_com.ISekaiScanCom object at 0x7f6f4ae44c50>
    │               └ <manga_py.providers.isekaiscan_com.ISekaiScanCom object at 0x7f6f4ae44c50>
    └ <manga_py.providers.isekaiscan_com.ISekaiScanCom object at 0x7f6f4ae44c50>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/providers/rawdevart_com_old.py", line 28, in get_chapters
    items = self._elements('.wp-manga-chapter > a', items_content)
    │       │                                       └ <Response [200]>
    │       └ <manga_py.providers.isekaiscan_com.ISekaiScanCom object at 0x7f6f4ae44c50>
    └ []
  File "/usr/local/lib/python3.6/dist-packages/manga_py/providers/helpers/std.py", line 15, in _elements
    return self.document_fromstring(content, selector)
           │                        │        └ '.wp-manga-chapter > a'
           │                        └ <Response [200]>
           └ <manga_py.providers.isekaiscan_com.ISekaiScanCom object at 0x7f6f4ae44c50>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/base_classes/static.py", line 20, in document_fromstring
    result = document_fromstring(body)  # todo
             │                   └ <Response [200]>
             └ <function document_fromstring at 0x7f6f4bcd7048>
  File "/usr/lib/python3/dist-packages/lxml/html/__init__.py", line 762, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
            │                │     │         └ {}
            │                │     └ <lxml.html.HTMLParser object at 0x7f6f4bce5048>
            │                └ <Response [200]>
            └ <module 'lxml.etree' from '/usr/lib/python3/dist-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so'>
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseMemoryDocument
ValueError: can only parse strings
```

**Comment by gromenauer** [comment]
Yep, works great :) :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 20.04.1 LTS
Python version | Python 3.8.2
Pip version | pip 20.0.2 
Npm version | 6.14.4
Manga-py version | 1.22.1
URL | `https://isekaiscan.com/manga/the-ultimate-middle-aged-hunter-travels-to-another-world-this-time-he-wants-to-live-a-slow-and-peaceful-life/`
