### ISSUE TITLE
[BUG] ninemanga.com . IndexError: list index out of range

### ISSUE THREAD

**Issue by gromenauer** [manga-py/manga-py#333]
# Bug report
Environment

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.21
URL | `https://www.ninemanga.com/manga/BIJO+TO+KENJA+TO+MAJIN+NO+KEN.html`
 
#### To Reproduce:

``` bash
docker run \
  --interactive --tty --rm --name manga-py \
  -v $PWD:/home/manga/Manga --entrypoint manga-py \
  mangadl/manga-py \
    --destination /home/manga/Manga --cbz --zero-fill \
    --rename-pages --no-webp --show-current-chapter-info \
    https://www.ninemanga.com/manga/BIJO+TO+KENJA+TO+MAJIN+NO+KEN.html
```

#### Additional context
Output:

``` py
"WARNING:/manga_py/parser.py:52:2020-09-06 10:12:46,934:Manga url changed! New url: https://www.gardenmanage.com/"
Traceback (most recent call last):
  File "/usr/local/bin/manga-py", line 11, in <module>
    load_entry_point('manga-py==1.21', 'console_scripts', 'manga-py')()
    └ <function load_entry_point at 0x7fabbb1a49d8>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7fabb5776840>
    └ <built-in function exit>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7fabb5776730>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7fabb5778ac8>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7fabb5778a90>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7fabb5778b00>
    │                     └ <manga_py.parser.Parser object at 0x7fabb5778b00>
    └ <manga_py.parser.Parser object at 0x7fabb5778b00>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 95, in process
    info('Manga name: %s' % self.manga_name)
    │                       └ <manga_py.providers.ninemanga_com.NineMangaCom object at 0x7fabb5778c88>
    └ <function info at 0x7fabbb148268>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/base_classes/params.py", line 17, in manga_name
    name = self.get_manga_name()
    │      └ <manga_py.providers.ninemanga_com.NineMangaCom object at 0x7fabb5778c88>
    └ None
  File "/usr/local/lib/python3.6/dist-packages/manga_py/providers/ninemanga_com.py", line 21, in get_manga_name
    url = self.html_fromstring(self.get_url(), '.subgiude > li + li > a', 0).get('href')
          │                    └ <manga_py.providers.ninemanga_com.NineMangaCom object at 0x7fabb5778c88>
          └ <manga_py.providers.ninemanga_com.NineMangaCom object at 0x7fabb5778c88>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/provider.py", line 256, in html_fromstring
    return self.document_fromstring(self.http_get(url, **params), selector, idx)
           │                        │             │      │        │         └ 0
           │                        │             │      │        └ '.subgiude > li + li > a'
           │                        │             │      └ {}
           │                        │             └ 'https://www.gardenmanage.com/'
           │                        └ <manga_py.providers.ninemanga_com.NineMangaCom object at 0x7fabb5778c88>
           └ <manga_py.providers.ninemanga_com.NineMangaCom object at 0x7fabb5778c88>
  File "/usr/local/lib/python3.6/dist-packages/manga_py/base_classes/static.py", line 24, in document_fromstring
    result = result[idx]
    │        │      └ 0
    │        └ []
    └ []
IndexError: list index out of range

```

**Comment by 1271** [comment]
Fixed. Sorry for long time a wait

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
Docker | 🐳 ✔
OS | Ubuntu 18.04.5 LTS
Python version | Python 3.6.9
Pip version | pip 9.0.1 
Npm version | 3.5.2
Manga-py version | 1.22
URL | `https://www.ninemanga.com/manga/BIJO+TO+KENJA+TO+MAJIN+NO+KEN.html`
