### ISSUE TITLE
embedded example doesnt work

### ISSUE THREAD

**Issue by vista-narvas** [manga-py/manga-py#338]
# Bug report

Description | Data
---|---
OS | Archlinux
Python version | 3.8
Pip version | 20.1.1
Manga-py version | 1.19.15
URL | any

#### To Reproduce:  
1. Step 1  
copy example from https://github.com/manga-py/manga-py/blob/stable_1.x/embedded.md  
1. Step 2  
add `#! /usr/bin/env python3` to the top  
```
test = MyAwesomeClass()  
test.start()
```
to the botom
1. Step 3
make executable and run
1. Step 4
get error
```
Traceback (most recent call last):
  File "./manga-subscriptions.py", line 71, in <module>
    test.start()
  File "./manga-subscriptions.py", line 28, in start
    self.parser = Parser(self.args)
  File "/home/storage/vista/.local/lib/python3.8/site-packages/manga_py/parser.py", line 18, in __init__
    self._add_params(args)
  File "/home/storage/vista/.local/lib/python3.8/site-packages/manga_py/parser.py", line 24, in _add_params
    params = params.parse_args()
AttributeError: 'dict' object has no attribute 'parse_args'
```

#### Additional context
even when i use a Namespace as args `args = argparse.Namespace()`
i get the same error `AttributeError: 'Namespace' object has no attribute 'parse_args'`

**Comment by 1271** [comment]
See it
 https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/cli/args.py#L50
 https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/parser.py#L20

You don't need a argparse.Namespace , but an ArgumentParser
(you can also overload the method if needed)

**Comment by vista-narvas** [comment]
ok, so supplying a dict or namespace doesn't work like it says in the example ?
```
    """
    is just a Namespace or dict with arguments
     (filled below. You can implement your implementation. The main thing is to have all keys possible)
    see manga_py.cli.args.get_cli_arguments()
    """
```
```
    args = {}
OR
    args = get_cli_arguments().parse_args({'https://manganelo.com/manga/read_the_gamer_manga_online_free'})
```
I’m looking for a way to circumvent ArgumentParser or fake a input for it

if i use `args = argparse.ArgumentParser()` i get the error `AttributeError: 'ArgumentParser' object has no attribute 'url'`  

and if i use `args = manga_py.cli.args.get_cli_arguments()` i get the default `the following arguments are required: URL`  
  
---
  
i tried using my own ArgumentParser class
```
class MyAwesomeFakeArgumentParser:
    url = "https://manganelo.com/manga/tower_of_god_manga"
    def parse_args(self):
        return argparse.Namespace(url=self.url)

class MyAwesomeClass:
    args = MyAwesomeFakeArgumentParser()
```
this gets stuck on
```
  File "/home/storage/vista/.local/lib/python3.8/site-packages/manga_py/provider.py", line 284, in __manual_ua
    return self._params['cookies'] and len(self._params['cookies']) and self._params['user_agent'] and len(self._params['user_agent'])
KeyError: 'cookies'
```

i feel like I'm missing the most obvious solution  
but i think i tried everything

**Comment by 1271** [comment]
manga-py requires many different parameters to work (even if they are not explicitly passed)
You can see all the parameters if you look here: https://github.com/manga-py/manga-py/tree/stable_1.x/manga_py/cli
Example "url" param: https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/cli/_args_general.py#L7

You can overload the `def _add_params(self, params: ArgumentParser=None):` [see it](https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/parser.py#L20) method and create a default word in it with all the keys from manga_py.cli

**Comment by 1271** [comment]
Example:

```python
import manga_py.parser

class MyParser(Parser):
  def _add_params(self, params: ArgumentParser = None):
    self.params = {
      "url": "http://manga/url",
      "cookies": [
        "key=value",
        "key2=value2",
         ... 
      ]} # and other keys

```

**Comment by 1271** [comment]
Did you succeed?
