### ISSUE TITLE
Mangadex issue when redirecting to another site

### ISSUE THREAD

**Issue by vmdude** [manga-py/manga-py#358]
# Bug report

Just found that some chapter are not hosted on `mangadex` website despite the fact that they're listed in the chapter list, thus parsed by `manga-py`, for instance (https://mangadex.org/chapter/670565):

![image](https://user-images.githubusercontent.com/1384259/103150100-d75c6d00-4770-11eb-895f-9dcb70eba15c.png)

This generate issues during download:

```text
$ manga-py https://mangadex.org/title/15016/black-clover --arguments language=gb
[KeyError('server')]
[KeyError('server')]
[KeyError('server')]
```

Environment (please complete the following information):

Description | Data
---|---
OS | MacOS Catalina 10.15.7
Python version | 3.9.0
Pip version | 20.2.4
Manga-py version | 1.25.0
URL | https://mangadex.org/title/15016/black-clover/ and https://mangadex.org/chapter/670565

#### To Reproduce:
1. Run `manga-py` to download from `mangadex` when there is a redirection to another site

#### Additional context
After looking at the debug messages:

```text
$ manga-py -c 1 --debug https://mangadex.org/title/15016/black-clover --arguments language=gb
"INFO:/manga_py/provider.py:111:2020-12-26 11:46:39,460:Manga name: Black Clover"
"INFO:/manga_py/provider.py:112:2020-12-26 11:46:39,460:Content length 4"
"INFO:/manga_py/provider.py:114:2020-12-26 11:46:40,947:Chapters received (7)"
"INFO:/manga_py/provider.py:125:2020-12-26 11:46:40,947:User-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0""
"INFO:/manga_py/provider.py:172:2020-12-26 11:46:41,069:Processed chapter 0 / {'id': 670565, 'hash': '8b32c7d9cc87a154e2739778a531e2f7', 'mangaId': 15016, 'mangaTitle': 'Black Clover', 'volume': '1', 'chapter': '1', 'title': "The Boy's Vow", 'language': 'gb', 'groups': [9097], 'uploader': 1756, 'timestamp': 1564097385, 'comments': 0, 'views': 12605}"
{'id': 670565, 'hash': '8b32c7d9cc87a154e2739778a531e2f7', 'mangaId': 15016, 'mangaTitle': 'Black Clover', 'volume': '1', 'chapter': '1', 'title': "The Boy's Vow", 'language': 'gb', 'groups': [{'id': 9097, 'name': 'MangaPlus'}], 'uploader': 1756, 'timestamp': 1564097385, 'comments': 0, 'views': 12589, 'status': 'external', 'pages': 'https://mangaplus.shueisha.co.jp/viewer/1000177'}
Traceback (most recent call last):
  File "/Users/frederic/Library/Python/3.9/bin/manga-py", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x1107ddee0>
    └ <module 'sys' (built-in)>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x1107ddd30>
    └ <built-in function exit>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x1107ddc10>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x1107e36d0>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/cli/__init__.py", line 47, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x1107e3520>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/parser.py", line 63, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x1107e3820>
    │                     └ <manga_py.parser.Parser object at 0x1107e3820>
    └ <manga_py.parser.Parser object at 0x1107e3820>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/provider.py", line 140, in process
    self.loop_chapters()
    └ <manga_py.providers.mangadex_org_v2.MangaDexOrg object at 0x110815070>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/provider.py", line 176, in loop_chapters
    self._download_chapter()
    └ <manga_py.providers.mangadex_org_v2.MangaDexOrg object at 0x110815070>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/provider.py", line 158, in _download_chapter
    raise e
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/provider.py", line 153, in _download_chapter
    self._storage['files'] = self.get_files()
    │                        └ <manga_py.providers.mangadex_org_v2.MangaDexOrg object at 0x110815070>
    └ <manga_py.providers.mangadex_org_v2.MangaDexOrg object at 0x110815070>
  File "/Users/frederic/Library/Python/3.9/lib/python/site-packages/manga_py/providers/mangadex_org_v2.py", line 97, in get_files
    server = content['server']
             └ {'id': 670565, 'hash': '8b32c7d9cc87a154e2739778a531e2f7', 'mangaId': 15016, 'mangaTitle': 'Black Clover', 'volume': '1', 'chapt...
KeyError: 'server'
```

It seems that the data retrieve during:

https://github.com/manga-py/manga-py/blob/d0be627e5425020053b4fb117a9b3f0d79b20c9e/manga_py/providers/mangadex_org_v2.py#L95

does not contain `server` key when there is a redirection, to confirm I added some log during execution and got this contant from "normal" chapter:

```json
{
  "id": 61524,
  "hash": "66fe9623bb4a312a516d15568d1a90ca",
  "mangaId": 2777,
  "mangaTitle": "Bokurano",
  "volume": "1",
  "chapter": "1",
  "title": "Kokopelli ①",
  "language": "gb",
  "groups": [{ "id": 31, "name": "Mangascreener" }],
  "uploader": 1456,
  "timestamp": 1518144839,
  "comments": 1,
  "views": 7222,
  "status": "OK",
  "pages": [
    "x1.jpg",
    ...
    "x38.jpg"
  ],
  "server": "https://s2.mangadex.org/data/"
}
```

and this content from redirected one:

```json
{
  "id": 670565,
  "hash": "8b32c7d9cc87a154e2739778a531e2f7",
  "mangaId": 15016,
  "mangaTitle": "Black Clover",
  "volume": "1",
  "chapter": "1",
  "title": "The Boy's Vow",
  "language": "gb",
  "groups": [{ "id": 9097, "name": "MangaPlus" }],
  "uploader": 1756,
  "timestamp": 1564097385,
  "comments": 0,
  "views": 12589,
  "status": "external",
  "pages": "https://mangaplus.shueisha.co.jp/viewer/1000177"
}
```

A workaround to bypass this (and not raise error) could be to add some check after:

```python
    def get_files(self):
        content = self._get(f'chapter/{self.chapter["hash"]}').get('data', {})
        if 'server' not in content:
            return []
        server = content['server']
        _hash = content['hash']
        return [f'{server}{_hash}/{img}' for img in content['pages']]
```

**Comment by 1271** [comment]
Sections marked "moved" are licensed.
Thanks for the issue, a little later I will add a notification about this case.

**Comment by gromenauer** [comment]
You can close this. Mangadex is down, it's changing it's codebase from the ground up. It will need a new provider when it's back on-line.

**Comment by 1271** [comment]
WOW....
They refused to display ads in every possible way, supporting the existence of the project by supporting a few users.
Hope they come back. It was a really good project
