### ISSUE TITLE
https://mangaku.pro/ return No new chapter found,  mangaku.pro is new domain for http://mangaku.in

### ISSUE THREAD

**Issue by Wrrrrryyyy** [manga-py/manga-py#364]
Description | Data
---|---
OS |Windows 10
Python version | 3.8.6
Pip version | 20.3.3
Manga-py version | 1.25.0
URL | https://mangaku.pro/

i try to
`manga-py https://mangaku.pro/chongsa-chapter-20/`
but get following error
`
ERROR:\manga_py\cli\__init__.py:38:2021-01-17 16:03:32,504:Please check if your inputed domain is supported by manga-py: 
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
- https://yuru-yuri.github.io/manga-py/ (deprecated)
Make sure that your inputed URL is correct
Trace:"
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts\manga-py-script.py", line 33, in <module>
    sys.exit(load_entry_point('manga-py==1.25.0', 'console_scripts', 'manga-py')())
    |        -> <function importlib_load_entry_point at 0x00000208463A61F0>
    -> <module 'sys' (built-in)>
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 112, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x0000020849644790>
    -> <built-in function exit>
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline 
reading).\...
            -> <function _run_util at 0x0000020849644670>
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\manga_py\util.py", line 41, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x000002084963EB50>
    |   -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\... 
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 46, in start
    raise e
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\manga_py\cli\__init__.py", line 30, in start
    self.parser.init_provider(
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\manga_py\parser.py", line 41, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found`

i also try to change mangaku.pro to mangaku.in 
`manga-py https://mangaku.in/chongsa-chapter-20/`
but get the following result
`"WARNING:\manga_py\parser.py:52:2021-01-17 16:05:36,548:Manga url changed! New url: https://mangaku.pro/chongsa-chapter-20/"
"WARNING:\manga_py\base_classes\base.py:103:2021-01-17 16:05:40,412:Chapters list empty. Check https://mangaku.pro/chongsa-chapter-20/"        
No new chapters found`

**Comment by 1271** [comment]
Domain changed. Thanks for issue

**Comment by Wrrrrryyyy** [comment]
> Domain changed. Thanks for issue

also 
`manga-py https://mangaku.in/chongsa-chapter-20/`
get the following result
`"WARNING:\manga_py\base_classes\base.py:103:2021-01-17 16:10:04,620:Chapters list empty. Check https://komikcast.com/komik/solo-spell-caster/" 
No new chapters found`

i think manga-py need update for most of url that from indonesia

**Comment by 1271** [comment]
Ok, thanks

**Comment by Wrrrrryyyy** [comment]
> Ok, thanks

thank you

**Comment by 1271** [comment]
Please, check version `1.26.0`
