### ISSUE TITLE
[Bug] save-manga-info crashes manga-py

### ISSUE THREAD

**Issue by N0D4N** [manga-py/manga-py#365]
# Bug report
Manga-py crashes when downloading manga with --save-manga-info argument

Description | Data
---|---
OS | Ubuntu 20.04.02
Python version | 3.8.5
Pip version | 20.0.2
Manga-py version | 1.26.0
URL | https://mangadex.org/title/57650/bibliomania

#### To Reproduce:
1. execute `manga-py --save-manga-info https://mangadex.org/title/57650/bibliomania --arguments language=gb` in your terminal

#### Additional context
Traceback
```py
Traceback (most recent call last):
  File "manga-py", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x7f5abda08820>
    └ <module 'sys' (built-in)>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f5abda08670>
    └ <built-in function exit>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f5abda08550>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x7f5abda0e4f0>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/cli/__init__.py", line 48, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x7f5abda0e100>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/parser.py", line 65, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x7f5abda0e190>
    │                     └ <manga_py.parser.Parser object at 0x7f5abda0e190>
    └ <manga_py.parser.Parser object at 0x7f5abda0e190>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/provider.py", line 86, in process
    self.prepare_download(url, params)
    │                     │    └ {'url': 'https://mangadex.org/title/57650/bibliomania', 'name': '', 'destination': 'Manga', 'no_progress': False, 'global_progre...
    │                     └ 'https://mangadex.org/title/57650/bibliomania'
    └ <manga_py.providers.mangadex_org_v2.MangaDexOrg object at 0x7f5abdabf460>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/provider.py", line 128, in prepare_download
    details = self.manga_details()
              └ <manga_py.providers.mangadex_org_v2.MangaDexOrg object at 0x7f5abdabf460>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/manga_py/providers/mangadex_org_v2.py", line 162, in manga_details
    'authors': [author for author in {self.__content['author'], self.__content['artist']} if author != ''],
TypeError: unhashable type: 'list'
```

**Comment by 1271** [comment]
Thanks for issue.
Please, check version `>=1.26.1`

**Comment by N0D4N** [comment]
Works perfectly now, thanks
