### ISSUE TITLE
Request to add a site mangareader.cc

### ISSUE THREAD

**Issue by sugizo** [manga-py/manga-py#370]
# Request to add a site

Description | Data
---|---
Url to add | http://mangareader.cc

thanks

**Comment by 1271** [comment]
You can try "force" option (mangapanda already added)
```bash
manga-py --force-provider http://mangareader.com/manga/awesome-manga http//mangareader.cc/manga/awesome-manga
```
This will force manga-py to use the specified provider (see https://manga-py.com/)


Thanks for the issue, this will be updated in the next 24 hours.

**Comment by sugizo** [comment]
tested `--force-provider` not worked `AttributeError: Provider not found`
```
$ manga-py --force-provider http://mangareader.com/chapter/tales-of-demons-and-gods-chapter-1#1 http://mangareader.cc/chapter/tales-of-demons-and-gods-chapter-1#1
"ERROR:/manga_py/cli/__init__.py:39:2021-03-05 17:25:01,393:Please check if your inputed domain is supported by manga-py: 
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
- https://yuru-yuri.github.io/manga-py/ (deprecated)
Make sure that your inputed URL is correct
Trace:"
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/bin/manga-py", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x10e02fdc0>
    └ <module 'sys' (built-in)>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x10e02faf0>
    └ <built-in function exit>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x10e02f9d0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x10e02c9a0>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/cli/__init__.py", line 47, in start
    raise e
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/cli/__init__.py", line 30, in start
    self.parser.init_provider(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/parser.py", line 42, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found
```

**Comment by 1271** [comment]
![image](https://user-images.githubusercontent.com/1452243/110103136-a3c44180-7db6-11eb-8c7f-f94f818b3f18.png)

Please, check actual supported urls. Try `mangareader.net` or `mangareader.site`

**Comment by sugizo** [comment]
```
$ ls
$ manga-py --force-provider http://mangareader.net/chapter/tales-of-demons-and-gods-chapter-1#1 http://mangareader.cc/chapter/tales-of-demons-and-gods-chapter-1#1
"WARNING:/manga_py/base_classes/base.py:102:2021-03-05 18:20:42,660:Chapters list empty. Check http://mangareader.cc/chapter/tales-of-demons-and-gods-chapter-1#1"
No new chapters found
$ manga-py --force-provider http://mangareader.site/chapter/tales-of-demons-and-gods-chapter-1#1 http://mangareader.cc/chapter/tales-of-demons-and-gods-chapter-1#1
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
    │                   └ <urllib3.connection.HTTPSConnection object at 0x109652160>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x109619bb0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
    └ <urllib3.connection.HTTPSConnection object at 0x109652160>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
           └ <urllib3.connection.HTTPSConnection object at 0x109652160>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x109652160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x109652160>: Failed to establish a new connection: [Errno 8] ...
          │             │      └ '/graphql?query=%7Bmanga(x:mr01,slug:%22tales-of-demons-and-gods-chapter-1'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x109619bb0>
          └ <class 'urllib3.exceptions.MaxRetryError'>
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api2.mangahub.io', port=443): Max retries exceeded with url: /graphql?query=%7Bmanga(x:mr01,slug:%22tales-of-demons-and-gods-chapter-1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x109652160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/bin/manga-py", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x1095e5dc0>
    └ <module 'sys' (built-in)>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x1095e5af0>
    └ <built-in function exit>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x1095e59d0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x1095e29a0>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/cli/__init__.py", line 48, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x1095e2640>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/parser.py", line 65, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x1095e2730>
    │                     └ <manga_py.parser.Parser object at 0x1095e2730>
    └ <manga_py.parser.Parser object at 0x1095e2730>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/provider.py", line 86, in process
    self.prepare_download(url, params)
    │                     │    └ {'url': 'http://mangareader.cc/chapter/tales-of-demons-and-gods-chapter-1#1', 'name': '', 'destination': 'Manga', 'no_progress':...
    │                     └ 'http://mangareader.cc/chapter/tales-of-demons-and-gods-chapter-1#1'
    └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x1095e28b0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/provider.py", line 113, in prepare_download
    self.chapters = self._prepare_chapters(self.get_chapters())
    │               │                      └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x1095e28b0>
    │               └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x1095e28b0>
    └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x1095e28b0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/providers/mangareader_site.py", line 12, in get_chapters
    chapters = self.json.loads(self.http_get(self.__graphql.format(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/base_classes/base.py", line 74, in http_get
    return self.http().get(url=url, headers=headers, cookies=cookies)
           │                   │            │                └ None
           │                   │            └ None
           │                   └ 'https://api2.mangahub.io/graphql?query={manga(x:mr01,slug:"tales-of-demons-and-gods-chapter-1#1"){chapters{id,number,title,slug...
           └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x1095e28b0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/http/request.py", line 104, in get
    response = self.requests(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/http/request.py", line 96, in requests
    self.response = self._requests_helper(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/http/request.py", line 67, in _requests_helper
    r = requests.request(method, url, **kwargs)
        │                │       │      └ {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0', 'Referer': 'http://...
        │                │       └ 'https://api2.mangahub.io/graphql?query={manga(x:mr01,slug:"tales-of-demons-and-gods-chapter-1#1"){chapters{id,number,title,slug...
        │                └ 'get'
        └ <module 'requests' from '/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/__init__.py'>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │                      │           │      └ {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0', 'Referer': 'http://...
           │                      │           └ 'https://api2.mangahub.io/graphql?query={manga(x:mr01,slug:"tales-of-demons-and-gods-chapter-1#1"){chapters{id,number,title,slug...
           │                      └ 'get'
           └ <requests.sessions.Session object at 0x1095e2b80>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [GET]>
           └ <requests.sessions.Session object at 0x1095e2b80>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │            │          └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │            └ <PreparedRequest [GET]>
        └ <requests.adapters.HTTPAdapter object at 0x1095e2c10>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
          │                          └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.ConnectionError'>
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api2.mangahub.io', port=443): Max retries exceeded with url: /graphql?query=%7Bmanga(x:mr01,slug:%22tales-of-demons-and-gods-chapter-1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x109652160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
