### ISSUE TITLE
[Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by sugizo** [manga-py/manga-py#371]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Darwin
Python version | 3.8.8
Pip version | 21.0.1
Manga-py version | 1.26.3
URL | http://mangareader.site/chapter/kenji/

#### To Reproduce:
1. `$ manga-py http://mangareader.site/chapter/kenji/`
1. `$ manga-py http://mangareader.site/chapter/kenji/chapter-1`
1. `$ manga-py https://mangareader.site/chapter/kenji/`
1. `$ manga-py https://mangareader.site/chapter/kenji/chapter-1`

#### Additional context
```
Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
    │                   └ <urllib3.connection.HTTPSConnection object at 0x10fb683d0>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x10fb31b20>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
    └ <urllib3.connection.HTTPSConnection object at 0x10fb683d0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
           └ <urllib3.connection.HTTPSConnection object at 0x10fb683d0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x10fb683d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fb683d0>: Failed to establish a new connection: [Errno 8] ...
          │             │      └ '/graphql?query=%7Bmanga(x:mr01,slug:%22kenji%22)%7Bchapters%7Bid,number,title,slug,date%7D%7D%7D'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x10fb31b20>
          └ <class 'urllib3.exceptions.MaxRetryError'>
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api2.mangahub.io', port=443): Max retries exceeded with url: /graphql?query=%7Bmanga(x:mr01,slug:%22kenji%22)%7Bchapters%7Bid,number,title,slug,date%7D%7D%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fb683d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sugizo/miniconda3/envs/python3_test/bin/manga-py", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x10fafedc0>
    └ <module 'sys' (built-in)>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x10fafeaf0>
    └ <built-in function exit>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x10fafe9d0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(args, _info).start()
    │   │     └ <manga_py.info.Info object at 0x10fafa9a0>
    │   └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    └ <class 'manga_py.cli.Cli'>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/cli/__init__.py", line 48, in start
    self.parser.start()
    └ <manga_py.cli.Cli object at 0x10fafa640>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/parser.py", line 65, in start
    self.provider.process(self.params['url'], self.params)
    │                     │                   └ <manga_py.parser.Parser object at 0x10fafa730>
    │                     └ <manga_py.parser.Parser object at 0x10fafa730>
    └ <manga_py.parser.Parser object at 0x10fafa730>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/provider.py", line 86, in process
    self.prepare_download(url, params)
    │                     │    └ {'url': 'https://mangareader.site/chapter/kenji/chapter-1', 'name': '', 'destination': 'Manga', 'no_progress': False, 'global_pr...
    │                     └ 'https://mangareader.site/chapter/kenji/chapter-1'
    └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x10fafa7f0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/provider.py", line 113, in prepare_download
    self.chapters = self._prepare_chapters(self.get_chapters())
    │               │                      └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x10fafa7f0>
    │               └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x10fafa7f0>
    └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x10fafa7f0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/providers/mangareader_site.py", line 12, in get_chapters
    chapters = self.json.loads(self.http_get(self.__graphql.format(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/base_classes/base.py", line 74, in http_get
    return self.http().get(url=url, headers=headers, cookies=cookies)
           │                   │            │                └ None
           │                   │            └ None
           │                   └ 'https://api2.mangahub.io/graphql?query={manga(x:mr01,slug:"kenji"){chapters{id,number,title,slug,date}}}'
           └ <manga_py.providers.mangareader_site.MangaReaderSite object at 0x10fafa7f0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/http/request.py", line 104, in get
    response = self.requests(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/http/request.py", line 96, in requests
    self.response = self._requests_helper(
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/manga_py/http/request.py", line 67, in _requests_helper
    r = requests.request(method, url, **kwargs)
        │                │       │      └ {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0', 'Referer': 'https:/...
        │                │       └ 'https://api2.mangahub.io/graphql?query={manga(x:mr01,slug:"kenji"){chapters{id,number,title,slug,date}}}'
        │                └ 'get'
        └ <module 'requests' from '/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/__init__.py'>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │                      │           │      └ {'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0', 'Referer': 'https:/...
           │                      │           └ 'https://api2.mangahub.io/graphql?query={manga(x:mr01,slug:"kenji"){chapters{id,number,title,slug,date}}}'
           │                      └ 'get'
           └ <requests.sessions.Session object at 0x10fafac40>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │         │       └ {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │         └ <PreparedRequest [GET]>
           └ <requests.sessions.Session object at 0x10fafac40>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │            │          └ {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
        │            └ <PreparedRequest [GET]>
        └ <requests.adapters.HTTPAdapter object at 0x10fb250a0>
  File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
          │                          └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.ConnectionError'>
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api2.mangahub.io', port=443): Max retries exceeded with url: /graphql?query=%7Bmanga(x:mr01,slug:%22kenji%22)%7Bchapters%7Bid,number,title,slug,date%7D%7D%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10fb683d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Comment by 1271** [comment]
Thanks for issue

**Comment by 1271** [comment]
Hi, I will close this issue
If you have any questions, please create another one.
Thanks for using manga-py
