### ISSUE TITLE
ImportError: cannot import name 'UnidentifiedImageError'

### ISSUE THREAD

**Issue by paulolimac** [manga-py/manga-py#375]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Ubuntu 18.04
Python version | 3.6
Pip version | 20.1.1
Manga-py version | 1.29.0
URL | http://sensescans.com/reader/series/to_you_the_immortal/

#### To Reproduce:
1. `manga-py --rename-pages --cbz --max-volumes=1 --skip-volumes=2 --reverse-downloading --zero-fill http://sensescans.com/reader/series/to_you_the_immortal/`

#### Additional context
The output:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/manga-py", line 5, in <module>
    from manga_py.util import main
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/cli/__init__.py", line 11, in <module>
    from manga_py.parser import Parser
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/parser.py", line 6, in <module>
    from .provider import Provider
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/provider.py", line 10, in <module>
    from .base_classes import (
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/base_classes/__init__.py", line 2, in <module>
    from .archive import Archive
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/base_classes/archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "/home/user/.local/lib/python3.6/site-packages/manga_py/manga_image.py", line 7, in <module>
    from PIL import UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError'
```
I tried with others domains (ie: mangadex etc) and the error repeated at the same way.

**Comment by 1271** [comment]
thanks for the issue, i will check it

**Comment by 1271** [comment]
Please, check updates:
`pip install -U 'manga-py>=1.29.1'`

**Comment by paulolimac** [comment]
fast fixed!
worked like a charm!
thank you 😊
