### ISSUE TITLE
Request to add sublimemanga.com

### ISSUE THREAD

**Issue by toddashi** [manga-py/manga-py#388]
# Request to add a site

Description | Data
---|---
Url to add | https://www.sublimemanga.com/

This site is owned by Viz. It should use the same software as viz.com. Thanks!

**Comment by 1271** [comment]
Sorry, but this will not be added.
Only 1 chapter is provided for free accounts. Without a number.
I don't have a subscription, and trying to work with someone who has one is not realistic. Believe me 
If you have any other favorite sites I will try to help

**Comment by gromenauer** [comment]
@toddashi, have you tried to download from sublimemanga using `--force-provider` with a viz.com URL ?

**Comment by toddashi** [comment]
> @toddashi, have you tried to download from sublimemanga using `--force-provider` with a viz.com URL ?

Thanks! I just tried that, might be doing it wrong. I tried it several ways and checked previous issues to make sure I was using --force-provider right, and it looks right.

```
./manga-py --force-provider https://www.viz.com/shonenjump/one-piece --debug https://www.sublimemanga.com/read/manga/worlds-greatest-first-love-14/product/818 
"ERROR:/manga_py/cli/__init__.py:44:2021-04-24 10:21:47,566:Please check if your inputed domain is supported by manga-py: 
- https://manga-py.com/manga-py/#resources-list
- https://manga-py.github.io/manga-py/#resources-list (alternative)
Make sure that your inputed URL is correct
Trace:"
Traceback (most recent call last):
  File "./manga-py", line 8, in <module>
    sys.exit(main())
    │        └ <function main at 0x7f0e33d6f700>
    └ <module 'sys' (built-in)>
  File "/home/ashi/.local/lib/python3.8/site-packages/manga_py/util.py", line 112, in main
    exit(run_util(args))
    │    │        └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    │    └ <function run_util at 0x7f0e33d6f550>
    └ <built-in function exit>
  File "/home/ashi/.local/lib/python3.8/site-packages/manga_py/util.py", line 83, in run_util
    _info = _run_util(args)
            │         └ ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            └ <function _run_util at 0x7f0e33d6f430>
  File "/home/ashi/.local/lib/python3.8/site-packages/manga_py/util.py", line 41, in _run_util
    Cli(parse_args.__dict__, _info).start()
    │   │                    └ <manga_py.info.Info object at 0x7f0e33de7dc0>
    │   └ Namespace(_raw_params='./manga-py --force-provider https://www.viz.com/shonenjump/one-piece --debug https://www.sublimemanga.com...
    └ <class 'manga_py.cli.Cli'>
  File "/home/ashi/.local/lib/python3.8/site-packages/manga_py/cli/__init__.py", line 51, in start
    raise e
  File "/home/ashi/.local/lib/python3.8/site-packages/manga_py/cli/__init__.py", line 35, in start
    self.parser.init_provider(
  File "/home/ashi/.local/lib/python3.8/site-packages/manga_py/parser.py", line 29, in init_provider
    raise AttributeError('Provider not found')
AttributeError: Provider not found
```

**Comment by 1271** [comment]
viz changed the address of the manga?
When the provider was added, the address was like this: 

_viz\.com/shonenjump/chapters/_&lt;manga-name>

https://github.com/manga-py/manga-py/blob/1cf0f28a3acba473689f4f6bee75da4f74616664/manga_py/providers/__init__.py#L705-L707
