### ISSUE TITLE
lilymanga.com

### ISSUE THREAD

**Issue by Sydiepus** [manga-py/manga-py#403]
# Bug report

Description | Data
---|---
Url to add | https://lilymanga.com/
test url | https://lilymanga.com/ys/yove/

**I tried to add the site but ran into a problem**

```python
#lilymanga_com.py
from manga_py.provider import Provider
from .helpers.std import Std


class LilyMangaCom(Provider, Std):
    def get_chapter_index(self) -> str:
        return self.chapter[1]

    def get_content(self):
        print(self.http_get(self.re.search(     #print statement for debugging
            r'(https?://.+?/ys/[^/]+)',
            self.get_url()
        ).group(1)))
        return self.http_get(self.re.search(
            r'(https?://.+?/ys/[^/]+)',
            self.get_url()
        ).group(1))
    
    def get_manga_name(self) -> str:
        return self._get_name('/ys/([^/]+)').replace('-', ' ')

    def get_chapters(self):
        return self._elements('.page-content-listing a')

    def get_files(self):
        parser = self.html_fromstring(self.chapter[0])
        return self._images_helper(parser, '.page-break > img')

    def get_cover(self) -> str:
        return self._cover_from_content('.summary_image > a > img')



main = LilyMangaCom
```
whenever I try to download the manga with :

``` .\manga.py https://lilymanga.com/ys/yove/ ```

I get this output :

```html
<html><title>You are being redirected...</title>
<noscript>Javascript is required. Please enable javascript before you are allowed to see this page.</noscript>
<script>var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='bT0nWmJUOCcuc3Vic3RyKDMsIDEpICsiYSIuc2xpY2UoMCwxKSArICAnJyArIAonaVtmJy5jaGFyQXQoMikrU3RyaW5nLmZyb21DaGFyQ29kZSgweDM4KSArICI1IiArIFN0cmluZy5mcm9tQ2hhckNvZGUoMHg2NSkgKyAiY3N1Ii5zbGljZSgwLDEpICsgICcnICsnJysiZHN1Y3VyIi5jaGFyQXQoMCkrICcnICsiMiIuc2xpY2UoMCwxKSArICdmJyArICBTdHJpbmcuZnJvbUNoYXJDb2RlKDUyKSArIFN0cmluZy5mcm9tQ2hhckNvZGUoNDkpICsgJ3EwYycuY2hhckF0KDIpKyAnJyArJycrIjR6Ii5jaGFyQXQoMCkgKyAiNm0iLmNoYXJBdCgwKSArICAnJyArImNzZWMiLnN1YnN0cigwLDEpICsgJ21ONScuY2hhckF0KDIpKyc2JyArICAnSHNGNCcuc3Vic3RyKDMsIDEpICsiY3N1Ii5zbGljZSgwLDEpICsgICcnICsgCic7Yicuc2xpY2UoMSwyKStTdHJpbmcuZnJvbUNoYXJDb2RlKDB4MzUpICsgIiIgKyI5Ii5zbGljZSgwLDEpICsgICcnICsnJysiMSIgKyAiMXN1Ii5zbGljZSgwLDEpICsgIjVzZWMiLnN1YnN0cigwLDEpICsgU3RyaW5nLmZyb21DaGFyQ29kZSgweDYzKSArICIxIiArICAnJyArU3RyaW5nLmZyb21DaGFyQ29kZSgweDMyKSArICJieCIuY2hhckF0KDApICsgIjN1Ii5jaGFyQXQoMCkgKyBTdHJpbmcuZnJvbUNoYXJDb2RlKDk4KSArICcnO2RvY3VtZW50LmNvb2tpZT0nc3VzJy5jaGFyQXQoMikrJ3UnKycnKydjJysnc3V1Jy5jaGFyQXQoMikrJ3N1Y3VyJy5jaGFyQXQoNCkrICdpJysnX3MnLmNoYXJBdCgwKSsnY3N1Jy5jaGFyQXQoMCkgKydsJysnbycrJ3UnKydkJysncCcrJ3InKydvc3VjdXInLmNoYXJBdCgwKSsgJ3hzdWN1Jy5jaGFyQXQoMCkgICsneScrJ18nKyd1JysnJysndXN1Y3UnLmNoYXJBdCgwKSAgKydpc3VjdScuY2hhckF0KDApICArJ2QnKydzdWN1XycuY2hhckF0KDQpKyAnMCcrJ2NzdScuY2hhckF0KDApICsnOScrJzcnKycwJysnc3VjdWQnLmNoYXJBdCg0KSsgJzVzdWN1cicuY2hhckF0KDApKyAnOHN1Jy5jaGFyQXQoMCkgKycwJy5jaGFyQXQoMCkrIj0iICsgbSArICc7cGF0aD0vO21heC1hZ2U9ODY0MDAnOyBsb2NhdGlvbi5yZWxvYWQoKTs=';L=S.length;U=0;r='';var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';for(u=0;u<64;u++){s[A.charAt(u)]=u;}for(i=0;i<L;i++){c=s[S.charAt(i)];U=(U<<6)+c;l+=6;while(l>=8){((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));}}e(r);</script></html>

<html><title>You are being redirected...</title>
<noscript>Javascript is required. Please enable javascript before you are allowed to see this page.</noscript>
<script>var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='bT0nWmJUOCcuc3Vic3RyKDMsIDEpICsiYSIuc2xpY2UoMCwxKSArICAnJyArIAonaVtmJy5jaGFyQXQoMikrU3RyaW5nLmZyb21DaGFyQ29kZSgweDM4KSArICI1IiArIFN0cmluZy5mcm9tQ2hhckNvZGUoMHg2NSkgKyAiY3N1Ii5zbGljZSgwLDEpICsgICcnICsnJysiZHN1Y3VyIi5jaGFyQXQoMCkrICcnICsiMiIuc2xpY2UoMCwxKSArICdmJyArICBTdHJpbmcuZnJvbUNoYXJDb2RlKDUyKSArIFN0cmluZy5mcm9tQ2hhckNvZGUoNDkpICsgJ3EwYycuY2hhckF0KDIpKyAnJyArJycrIjR6Ii5jaGFyQXQoMCkgKyAiNm0iLmNoYXJBdCgwKSArICAnJyArImNzZWMiLnN1YnN0cigwLDEpICsgJ21ONScuY2hhckF0KDIpKyc2JyArICAnSHNGNCcuc3Vic3RyKDMsIDEpICsiY3N1Ii5zbGljZSgwLDEpICsgICcnICsgCic7Yicuc2xpY2UoMSwyKStTdHJpbmcuZnJvbUNoYXJDb2RlKDB4MzUpICsgIiIgKyI5Ii5zbGljZSgwLDEpICsgICcnICsnJysiMSIgKyAiMXN1Ii5zbGljZSgwLDEpICsgIjVzZWMiLnN1YnN0cigwLDEpICsgU3RyaW5nLmZyb21DaGFyQ29kZSgweDYzKSArICIxIiArICAnJyArU3RyaW5nLmZyb21DaGFyQ29kZSgweDMyKSArICJieCIuY2hhckF0KDApICsgIjN1Ii5jaGFyQXQoMCkgKyBTdHJpbmcuZnJvbUNoYXJDb2RlKDk4KSArICcnO2RvY3VtZW50LmNvb2tpZT0nc3VzJy5jaGFyQXQoMikrJ3UnKycnKydjJysnc3V1Jy5jaGFyQXQoMikrJ3N1Y3VyJy5jaGFyQXQoNCkrICdpJysnX3MnLmNoYXJBdCgwKSsnY3N1Jy5jaGFyQXQoMCkgKydsJysnbycrJ3UnKydkJysncCcrJ3InKydvc3VjdXInLmNoYXJBdCgwKSsgJ3hzdWN1Jy5jaGFyQXQoMCkgICsneScrJ18nKyd1JysnJysndXN1Y3UnLmNoYXJBdCgwKSAgKydpc3VjdScuY2hhckF0KDApICArJ2QnKydzdWN1XycuY2hhckF0KDQpKyAnMCcrJ2NzdScuY2hhckF0KDApICsnOScrJzcnKycwJysnc3VjdWQnLmNoYXJBdCg0KSsgJzVzdWN1cicuY2hhckF0KDApKyAnOHN1Jy5jaGFyQXQoMCkgKycwJy5jaGFyQXQoMCkrIj0iICsgbSArICc7cGF0aD0vO21heC1hZ2U9ODY0MDAnOyBsb2NhdGlvbi5yZWxvYWQoKTs=';L=S.length;U=0;r='';var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';for(u=0;u<64;u++){s[A.charAt(u)]=u;}for(i=0;i<L;i++){c=s[S.charAt(i)];U=(U<<6)+c;l+=6;while(l>=8){((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));}}e(r);</script></html>

"WARNING:\manga_py\base_classes\base.py:104:2021-06-21 19:01:32,554:Chapters list empty. Check https://lilymanga.com/ys/yove/"
No new chapters found
```

**Comment by Sydiepus** [comment]
Most of the code (all) is recycled from manganelo_com.py and genkan_io.py

**Comment by 1271** [comment]
Thanks for this issue.
This is a bug. I will try to fix it soon

**Comment by 1271** [comment]
Oh .. you need to bypass cloudflare restrictions 

Please, use `--cookies` and `--user-agent` options

**Comment by 1271** [comment]
I mean, I'll correct the provider, but you still need to specify cookies and user-agent for the site to work correctly.

**Comment by Sydiepus** [comment]
ohh okay then i'm supposed to used the --cookies and --user-agent to make it work right ?
then there's no way to get the cookies and change the user-agent before making the request because of cloudflare restriction ?

**Comment by 1271** [comment]
Yes something like that.

**Comment by 1271** [comment]
Those. you need to go to the site from your browser, copy the cookies and user-agent and specify them for the provider's correct work.

I will update the provider in the next 24 hours. Thank you for understanding

**Comment by Sydiepus** [comment]
thanks for the help.

**Comment by Sydiepus** [comment]
### provider test

![image](https://user-images.githubusercontent.com/49863809/123144300-3a9b3380-d464-11eb-8db8-41d3dc1f9f60.png)

### Command
```.\manga.py https://lilymanga.com/ys/words-and-spirits --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" --cookies sucuri_cloudproxy_uuid_19d9c7de7=9b95bc2f9f518b7e3b6f466268d54381```

### Output 
```html
<html><title>You are being redirected...</title>
<noscript>Javascript is required. Please enable javascript before you are allowed to see this page.</noscript>
<script>var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='cz0nPzcnLnNsaWNlKDEsMikrJ0k5Jy5zbGljZSgxLDIpKyc2aVlmJy5zdWJzdHIoMywgMSkgKyJkayIuY2hhckF0KDApICsgIjEiICsgIjRzdWN1ciIuY2hhckF0KDApKyIzIiArICI4c3VjdXIiLmNoYXJBdCgwKSsgJycgKydjJyArICAgJycgKycnKyJmc3UiLnNsaWNlKDAsMSkgKyAgJycgKyIxc3VjdXIiLmNoYXJBdCgwKSsiIiArImJzdWN1ciIuY2hhckF0KDApKyAnJyArIAonZScgKyAgICcnICsgCiI3c2VjIi5zdWJzdHIoMCwxKSArICdjJyArICAgJycgKyAKJzgnICsgICIiICsncDZiJy5jaGFyQXQoMikrIjkiICsgJz91RWEnLnN1YnN0cigzLCAxKSArJ1NzPWInLnN1YnN0cigzLCAxKSArU3RyaW5nLmZyb21DaGFyQ29kZSgxMDEpICsgIjlzZWMiLnN1YnN0cigwLDEpICsgICcnICsgCidUYkVmJy5zdWJzdHIoMywgMSkgKyc0dkBiJy5zdWJzdHIoMywgMSkgK1N0cmluZy5mcm9tQ2hhckNvZGUoMTAwKSArIFN0cmluZy5mcm9tQ2hhckNvZGUoMHg2MSkgKyAnYycgKyAgIjkiICsgICcnICsiMnN1Ii5zbGljZSgwLDEpICsgICcnICsiOSIgKyAgJycgK1N0cmluZy5mcm9tQ2hhckNvZGUoMHgzOSkgKyAiMnN1Y3VyIi5jaGFyQXQoMCkrIiIgKycnO2RvY3VtZW50LmNvb2tpZT0ncycrJ3VzJy5jaGFyQXQoMCkrJ2MnKyd1Jy5jaGFyQXQoMCkrJ3N1cicuY2hhckF0KDIpKydzdWknLmNoYXJBdCgyKSsnc3VjdXJpXycuY2hhckF0KDYpKydjJysnbCcrJycrJ29zJy5jaGFyQXQoMCkrJ3UnLmNoYXJBdCgwKSsnZHMnLmNoYXJBdCgwKSsncHMnLmNoYXJBdCgwKSsncicrJ29zdWMnLmNoYXJBdCgwKSsgJ3gnKycnKyd5c3VjJy5jaGFyQXQoMCkrICdfcycuY2hhckF0KDApKyd1JysndScrJycrJ3NpJy5jaGFyQXQoMSkrJ3N1Y3VyZCcuY2hhckF0KDUpICsgJ18nKyc0JysnZicrJycrJ3N1Y3VyaTMnLmNoYXJBdCg2KSsnYycrJzAnKydzdWN1cmljJy5jaGFyQXQoNikrJ3N1Y3VyaTcnLmNoYXJBdCg2KSsnOXN1Jy5jaGFyQXQoMCkgKydmc3VjdScuY2hhckF0KDApICArIj0iICsgcyArICc7cGF0aD0vO21heC1hZ2U9ODY0MDAnOyBsb2NhdGlvbi5yZWxvYWQoKTs=';L=S.length;U=0;r='';var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';for(u=0;u<64;u++){s[A.charAt(u)]=u;}for(i=0;i<L;i++){c=s[S.charAt(i)];U=(U<<6)+c;l+=6;while(l>=8){((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));}}e(r);</script></html>

<html><title>You are being redirected...</title>
<noscript>Javascript is required. Please enable javascript before you are allowed to see this page.</noscript>
<script>var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='cz0nPzcnLnNsaWNlKDEsMikrJ0k5Jy5zbGljZSgxLDIpKyc2aVlmJy5zdWJzdHIoMywgMSkgKyJkayIuY2hhckF0KDApICsgIjEiICsgIjRzdWN1ciIuY2hhckF0KDApKyIzIiArICI4c3VjdXIiLmNoYXJBdCgwKSsgJycgKydjJyArICAgJycgKycnKyJmc3UiLnNsaWNlKDAsMSkgKyAgJycgKyIxc3VjdXIiLmNoYXJBdCgwKSsiIiArImJzdWN1ciIuY2hhckF0KDApKyAnJyArIAonZScgKyAgICcnICsgCiI3c2VjIi5zdWJzdHIoMCwxKSArICdjJyArICAgJycgKyAKJzgnICsgICIiICsncDZiJy5jaGFyQXQoMikrIjkiICsgJz91RWEnLnN1YnN0cigzLCAxKSArJ1NzPWInLnN1YnN0cigzLCAxKSArU3RyaW5nLmZyb21DaGFyQ29kZSgxMDEpICsgIjlzZWMiLnN1YnN0cigwLDEpICsgICcnICsgCidUYkVmJy5zdWJzdHIoMywgMSkgKyc0dkBiJy5zdWJzdHIoMywgMSkgK1N0cmluZy5mcm9tQ2hhckNvZGUoMTAwKSArIFN0cmluZy5mcm9tQ2hhckNvZGUoMHg2MSkgKyAnYycgKyAgIjkiICsgICcnICsiMnN1Ii5zbGljZSgwLDEpICsgICcnICsiOSIgKyAgJycgK1N0cmluZy5mcm9tQ2hhckNvZGUoMHgzOSkgKyAiMnN1Y3VyIi5jaGFyQXQoMCkrIiIgKycnO2RvY3VtZW50LmNvb2tpZT0ncycrJ3VzJy5jaGFyQXQoMCkrJ2MnKyd1Jy5jaGFyQXQoMCkrJ3N1cicuY2hhckF0KDIpKydzdWknLmNoYXJBdCgyKSsnc3VjdXJpXycuY2hhckF0KDYpKydjJysnbCcrJycrJ29zJy5jaGFyQXQoMCkrJ3UnLmNoYXJBdCgwKSsnZHMnLmNoYXJBdCgwKSsncHMnLmNoYXJBdCgwKSsncicrJ29zdWMnLmNoYXJBdCgwKSsgJ3gnKycnKyd5c3VjJy5jaGFyQXQoMCkrICdfcycuY2hhckF0KDApKyd1JysndScrJycrJ3NpJy5jaGFyQXQoMSkrJ3N1Y3VyZCcuY2hhckF0KDUpICsgJ18nKyc0JysnZicrJycrJ3N1Y3VyaTMnLmNoYXJBdCg2KSsnYycrJzAnKydzdWN1cmljJy5jaGFyQXQoNikrJ3N1Y3VyaTcnLmNoYXJBdCg2KSsnOXN1Jy5jaGFyQXQoMCkgKydmc3VjdScuY2hhckF0KDApICArIj0iICsgcyArICc7cGF0aD0vO21heC1hZ2U9ODY0MDAnOyBsb2NhdGlvbi5yZWxvYWQoKTs=';L=S.length;U=0;r='';var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';for(u=0;u<64;u++){s[A.charAt(u)]=u;}for(i=0;i<L;i++){c=s[S.charAt(i)];U=(U<<6)+c;l+=6;while(l>=8){((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));}}e(r);</script></html>
```
```python
Traceback (most recent call last):
  File "C:\github\manga-py\manga.py", line 8, in <module>
    main()
    -> <function main at 0x000001AA083B14C0>
  File "C:\github\manga-py\manga_py\util.py", line 112, in main
    exit(run_util(args))
    |    |        -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
    |    -> <function run_util at 0x000001AA083B13A0>
    -> <built-in function exit>
  File "C:\github\manga-py\manga_py\util.py", line 83, in run_util
    _info = _run_util(args)
            |         -> ArgumentParser(prog='manga-py', usage=None, description='%(prog)s is the universal manga downloader (for your offline reading).\...
            -> <function _run_util at 0x000001AA083B1280>
  File "C:\github\manga-py\manga_py\util.py", line 41, in _run_util
    Cli(parse_args.__dict__, _info).start()
    |   |                    -> <manga_py.info.Info object at 0x000001AA083A2F10>
    |   -> Namespace(url='https://lilymanga.com/ys/words-and-spirits', name='', destination='Manga', no_progress=False, global_progress=Fal...
    -> <class 'manga_py.cli.Cli'>
  File "C:\github\manga-py\manga_py\cli\__init__.py", line 53, in start
    self.parser.start()
    -> <manga_py.cli.Cli object at 0x000001AA083BB1F0>
  File "C:\github\manga-py\manga_py\parser.py", line 52, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x000001AA083BB0D0>
    |                     -> <manga_py.parser.Parser object at 0x000001AA083BB0D0>
    -> <manga_py.parser.Parser object at 0x000001AA083BB0D0>
  File "C:\github\manga-py\manga_py\provider.py", line 89, in process
    self.prepare_download(params)
    |                     -> {'url': 'https://lilymanga.com/ys/words-and-spirits', 'name': '', 'destination': 'Manga', 'no_progress': False, 'global_progress...
    -> <manga_py.providers.lilymanga_com.LilyMangaCom object at 0x000001AA0837A910>
  File "C:\github\manga-py\manga_py\provider.py", line 117, in prepare_download
    self.chapters = self._prepare_chapters(self.get_chapters())
    |               |                      -> <manga_py.providers.lilymanga_com.LilyMangaCom object at 0x000001AA0837A910>
    |               -> <manga_py.providers.lilymanga_com.LilyMangaCom object at 0x000001AA0837A910>
    -> <manga_py.providers.lilymanga_com.LilyMangaCom object at 0x000001AA0837A910>
  File "C:\github\manga-py\manga_py\providers\lilymanga_com.py", line 16, in get_chapters
    manga_id = self._elements('#manga-chapters-holder')[0].get('data-id')
               -> <manga_py.providers.lilymanga_com.LilyMangaCom object at 0x000001AA0837A910>
IndexError: list index out of range
```

well as you saw it's not working the cookie can't be the issue since it expires in the next 24 hours. Not sure if i'm doing something wrong but thanks for trying. Dealing with cloudflare is a pain there's no need to force it.
Feel free to close the issue i might reopen it if i ever find a way to make it work.

**Comment by 1271** [comment]
Hmm ... This is weird because I tested it and it actually works for me.

Are you running manga-py on your PC right? The IP address should not be changed, because this is also part of the cloudflare protection

---

I'm check it again ... and it's working fine.
Perhaps your IP address has changed?

![изображение](https://user-images.githubusercontent.com/1452243/123174046-308b2c00-d488-11eb-80c1-aaf63ed76044.png)
![изображение](https://user-images.githubusercontent.com/1452243/123174148-587a8f80-d488-11eb-9241-c7a5ba21086b.png)

**Comment by Sydiepus** [comment]
how odd it could that my ip is being changed or blacklisted since i can't access some sites without refreshing 2 or 3 times. 
Thanks for your help i'll try to solve this problem on my end. 
i'll close the issue since it's working for you and probably other people too.

**Comment by 1271** [comment]
If it becomes possible to automate the process of obtaining a cloudflare token, the provider will receive this opportunity
