### ISSUE TITLE
Failed to create files, possibly due to invalid characters in directory name

### ISSUE THREAD

**Issue by glasshex** [manga-py/manga-py#418]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 10
Python version | Python Version 3.9.4
Pip version | 20.2.3
Manga-py version | 1.3.29.1
URL | https://nhentai.net/g/368760/

#### To Reproduce:
1. Command: manga-py https://nhentai.net/g/368760/

**Comment by glasshex** [comment]
`Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "c:\python\scripts\manga-py.exe\"...
         -> <code object <module> at 0x00000121674F4D40, file "c:\python\scripts\manga-py.exe\__main__.py", line 2>
  File "c:\python\scripts\manga-py.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |        -> <function main at 0x000001216A69DF70>
    -> <module 'sys' (built-in)>
  File "c:\python\lib\site-packages\manga_py\util.py", line 124, in main
    exit(run_util(args))
    |    |        -> {'url': 'https://nhentai.net/g/368760/', 'name': '', 'destination': 'Manga', 'no_progress': False, 'global_progress': False, 'ar...
    |    -> <function run_util at 0x000001216A69DE50>
    -> <built-in function exit>
  File "c:\python\lib\site-packages\manga_py\util.py", line 82, in run_util
    _info = _run_util(args)
            |         -> {'url': 'https://nhentai.net/g/368760/', 'name': '', 'destination': 'Manga', 'no_progress': False, 'global_progress': False, 'ar...
            -> <function _run_util at 0x000001216A69DD30>
  File "c:\python\lib\site-packages\manga_py\util.py", line 42, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x000001216A6987C0>
    |   -> {'url': 'https://nhentai.net/g/368760/', 'name': '', 'destination': 'Manga', 'no_progress': False, 'global_progress': False, 'ar...
    -> <class 'manga_py.cli.Cli'>
  File "c:\python\lib\site-packages\manga_py\cli\__init__.py", line 53, in start
    self.parser.start()
    -> <manga_py.cli.Cli object at 0x000001216A698790>
  File "c:\python\lib\site-packages\manga_py\parser.py", line 52, in start
    self.provider.process(self.params['url'], self.params)
    |                     |                   -> <manga_py.parser.Parser object at 0x000001216A6986D0>
    |                     -> <manga_py.parser.Parser object at 0x000001216A6986D0>
    -> <manga_py.parser.Parser object at 0x000001216A6986D0>
  File "c:\python\lib\site-packages\manga_py\provider.py", line 91, in process
    self.loop_chapters()
    -> <manga_py.providers.nhentai_net.nHentaiNet object at 0x00000121679E3F70>
  File "c:\python\lib\site-packages\manga_py\provider.py", line 173, in loop_chapters
    if dl.already_downloaded():
  File "c:\python\lib\site-packages\manga_py\download_methods.py", line 35, in already_downloaded
    return not_allow_archive and is_file(_path)
           |                     |       -> 'Manga\\[Amazake Hatosyo-ten (Yoshu Ohepe)] Shinyuu no Musume Saori [Kinyoubi, Asa 9:00, LoveHo...] [English] [SDTLs] [Digital]\...
           |                     -> <function is_file at 0x0000012169856820>
           -> True
  File "c:\python\lib\site-packages\manga_py\fs.py", line 57, in is_file
    return Path(_path).is_file()
           |    -> 'Manga\\[Amazake Hatosyo-ten (Yoshu Ohepe)] Shinyuu no Musume Saori [Kinyoubi, Asa 9:00, LoveHo...] [English] [SDTLs] [Digital]\...
           -> <class 'pathlib.Path'>
  File "c:\python\lib\pathlib.py", line 1439, in is_file
    return S_ISREG(self.stat().st_mode)
           |       -> WindowsPath('Manga/[Amazake Hatosyo-ten (Yoshu Ohepe)] Shinyuu no Musume Saori [Kinyoubi, Asa 9:00, LoveHo...] [English] [SDTLs]...
           -> <built-in function S_ISREG>
  File "c:\python\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
           |                   -> WindowsPath('Manga/[Amazake Hatosyo-ten (Yoshu Ohepe)] Shinyuu no Musume Saori [Kinyoubi, Asa 9:00, LoveHo...] [English] [SDTLs]...
           -> WindowsPath('Manga/[Amazake Hatosyo-ten (Yoshu Ohepe)] Shinyuu no Musume Saori [Kinyoubi, Asa 9:00, LoveHo...] [English] [SDTLs]...
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'Manga\\[Amazake Hatosyo-ten (Yoshu Ohepe)] Shinyuu no Musume Saori [Kinyoubi, Asa 9:00, LoveHo...] [English] [SDTLs] [Digital]\\HentaiFox_archive.zip'`

**Comment by glasshex** [comment]
[log.txt](https://github.com/manga-py/manga-py/files/6960024/log.txt)

**Comment by 1271** [comment]
Thanks for the issue

**Comment by 1271** [comment]
hmm ... i will check it on windows
Thank you!
