### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by Kuchizu** [manga-py/manga-py#426]
C:\Users\HP\Desktop>py -V
Python 3.10.0

C:\Users\HP\Desktop>pip list
Package                   Version
------------------------- ---------
aiofiles                  0.4.0
aiogram                   2.18
aiograph                  0.2
aiohttp                   3.6.2
aioify                    0.4.0
aiosignal                 1.2.0
altgraph                  0.17.2
anipics                   1.4
anyio                     3.4.0
asgiref                   3.4.1
async-generator           1.10
async-lru                 1.0.2
async-timeout             3.0.1
attrs                     19.3.0
Babel                     2.9.1
beautifulsoup4            4.8.1
better-exceptions         0.3.3
bidict                    0.21.4
certifi                   2019.9.11
cffi                      1.15.0
cfscrape                  2.1.1
chardet                   3.0.4
charset-normalizer        2.0.7
click                     8.0.3
cloudscraper              1.2.58
colorama                  0.4.4
configparser              5.2.0
console-progressbar       1.1.2
crayons                   0.4.0
cryptography              36.0.1
cssselect                 1.1.0
defusedxml                0.7.1
Django                    4.0.1
EasyProcess               0.3
entrypoint2               0.2.4
fastapi                   0.71.0
ffmpy                     0.3.0
Flask                     2.0.2
Flask-SocketIO            5.1.1
fpdf                      1.7.2
frozenlist                1.2.0
future                    0.18.2
geckodriver-autoinstaller 0.1.0
gevent                    21.12.0
greenlet                  1.1.2
gunicorn                  20.1.0
h11                       0.12.0
hentai                    3.2.9
hentai-chan-api-async     1.0.0
heroku                    0.1.4
httptools                 0.3.0
idna                      2.8
ifaddr                    0.1.7
image                     1.5.33
itsdangerous              2.0.1
jedi                      0.18.1
Jinja2                    3.0.3
keyboard                  0.13.5
librespot                 0.0.1
lxml                      4.7.1
manga-py                  1.32.0
MarkupSafe                2.0.1
module-wrapper            0.3.1
mss                       6.1.0
multidict                 4.5.2
music-tag                 0.4.3
mutagen                   1.45.1
outcome                   1.1.0
packaging                 21.3
parso                     0.8.3
pefile                    2021.9.3
Pillow                    8.4.0
pip                       21.2.3
progressbar2              4.0.0
protobuf                  3.19.1
psycopg2                  2.9.3
pyaes                     1.6.1
pycparser                 2.21
pycryptodome              3.12.0
pycryptodomex             3.11.0
pydantic                  1.9.0
pydub                     0.25.1
PyExecJS                  1.5.1
pygame                    2.1.0
pyinstaller               4.7
pyinstaller-hooks-contrib 2021.4
PyMySQL                   1.0.2
PyOgg                     0.6.14a1
pyOpenSSL                 21.0.0
pyparsing                 3.0.7
Pyrogram                  1.2.20
pyscreenshot              3.0
PySocks                   1.7.1
pyTelegramBotAPI          4.1.1
python-dateutil           1.5
python-dotenv             0.19.2
python-engineio           4.3.0
python-socketio           5.5.0
python-utils              3.1.0
pytube                    11.0.2
pytz                      2021.3
pywebio                   1.4.0
pywin32-ctypes            0.2.0
PyYAML                    6.0
requests                  2.24.0
requests-futures          1.0.0
requests-toolbelt         0.9.1
schedule                  1.1.0
selenium                  3.141.0
setuptools                57.4.0
six                       1.16.0
sniffio                   1.2.0
sortedcontainers          2.4.0
soupsieve                 1.9.4
sqlparse                  0.4.2
starlette                 0.17.1
stdlib-list               0.8.0
stem                      1.8.0
tabulate                  0.8.9
telegraph                 2.1.0
toml                      0.10.2
tornado                   6.1
torrequest                0.1.0
tqdm                      4.62.3
trio                      0.19.0
trio-websocket            0.9.2
turtle                    0.0.1
typing-extensions         3.10.0.2
tzdata                    2021.5
ua-parser                 0.10.0
urllib3                   1.25.6
user-agents               2.2.0
uvicorn                   0.16.0
Wand                      0.6.7
watchgod                  0.7
webdriver-manager         3.5.2
websocket                 0.2.1
websocket-client          1.2.1
websockets                10.1
Werkzeug                  2.0.2
wget                      3.2
wsproto                   1.0.0
yarl                      1.3.0
youtube-search            2.1.0
zeroconf                  0.37.0
zope.event                4.5.0
zope.interface            5.4.0

C:\Users\HP\Desktop>manga-py bleach
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\Scripts\manga-py.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\cli\__init__.py", line 11, in <module>
    from manga_py.parser import Parser
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\parser.py", line 6, in <module>
    from .provider import Provider
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\provider.py", line 10, in <module>
    from .base_classes import (
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\base_classes\__init__.py", line 2, in <module>
    from .archive import Archive
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\base_classes\archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\manga_image.py", line 5, in <module>
    from PIL import Image as PilImage, ImageChops, ImageFile
ModuleNotFoundError: No module named 'PIL'

Как быть ?

**Comment by 1271** [comment]
Please run this command

```bash
manga-py --debug-version
```

And show result. Thank you

**Comment by Kuchizu** [comment]
> Please run this command
> 
> ```shell
> manga-py --debug-version
> ```
> 
> And show result. Thank you

C:\Users\HP>manga-py --debug-version
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\Scripts\manga-py.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\cli\__init__.py", line 11, in <module>
    from manga_py.parser import Parser
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\parser.py", line 6, in <module>
    from .provider import Provider
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\provider.py", line 10, in <module>
    from .base_classes import (
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\base_classes\__init__.py", line 2, in <module>
    from .archive import Archive
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\base_classes\archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\manga_image.py", line 5, in <module>
    from PIL import Image as PilImage, ImageChops, ImageFile
ModuleNotFoundError: No module named 'PIL'

**Comment by 1271** [comment]
Oh...  Try this:

pip version:
```bash
pip --version
```

install pillow package for your python:
```bash
py -m pip install pillow~=8.3 lxml
```

**Comment by 1271** [comment]
I will fix this bug in the next release.
Thanks for the issue 

```bash
manga-py --debug-version
```
Component | Version
---       | ---
OS        | Windows-10-10.0.22000-SP0
python    | 3.10.2
pip       | 21.2.4
manga-py  | 1.32.0

Module                 | Version
---                    | ---
Pillow~=8.1            | 8.4.0
PyExecJS>=1.5          | 1.5.1
better_exceptions>=0.2 | 0.3.3
cloudscraper           | 1.2.58
cssselect>=1.1         | 1.1.0
lxml~=4.6              | 4.7.1
packaging>=20.3        | 21.3
progressbar2>=3.50     | 4.0.0
pycryptodome>=3.9      | 3.12.0
pysocks>=1.7           | 1.7.1
requests>=2.23         | 2.27.1
toml>=0.10             | 0.10.2

**Comment by Kuchizu** [comment]
> ```shell
> ```shell
> manga-py --debug-version
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

I'm still getting that error(

C:\Users\HP>pip --version
pip 21.2.3 from C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)

C:\Users\HP>py -m pip install pillow~=8.3 lxml
Requirement already satisfied: pillow~=8.3 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (8.4.0)
Requirement already satisfied: lxml in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (4.7.1)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\HP>manga-py --debug-version
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\Scripts\manga-py.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\util.py", line 10, in <module>
    from .cli.args import get_cli_arguments
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\cli\__init__.py", line 11, in <module>
    from manga_py.parser import Parser
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\parser.py", line 6, in <module>
    from .provider import Provider
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\provider.py", line 10, in <module>
    from .base_classes import (
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\base_classes\__init__.py", line 2, in <module>
    from .archive import Archive
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\base_classes\archive.py", line 6, in <module>
    from manga_py.manga_image import MangaImage
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\manga_py\manga_image.py", line 5, in <module>
    from PIL import Image as PilImage, ImageChops, ImageFile
ModuleNotFoundError: No module named 'PIL'

**Comment by 1271** [comment]
Hm.. That's strange. I installed python on windows and it works. 

Try this, please:

Run python:

```bash
python  # or `py` for you
```
then into python:
```python
from PIL import Image

Image.__version__
```

It's worked?

**Comment by Kuchizu** [comment]
> Hm.. That's strange. I installed python on windows and it works.
> 
> Try this, please:
> 
> Run python:
> 
> ```shell
> python  # or `py` for you
> ```
> 
> then into python:
> 
> ```python
> from PIL import Image
> 
> Image.__version__
> ```
> 
> It's worked?

C:\Users\HP>pip show pillow
Name: Pillow
Version: 8.4.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: c:\users\hp\appdata\local\programs\python\python310\lib\site-packages
Requires:
Required-by: image

C:\Users\HP>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'
>>>
>>> Image.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Image' is not defined

I don't know i'm still getting the same error, maybe i should install another version of python ?

**Comment by Kuchizu** [comment]
Oh I just deleted all pips and installed python 3.9.6 and it worked, thank you :)
