### ISSUE TITLE
nhentai not working? | I know it needs flaresolver. I read the documentation on Flaresolver but still no clue..

### ISSUE THREAD

**Issue by ShinoIro** [manga-py/manga-py#447]
so, i downloaded the flaresolver, using windows, then i opened it the last line was this "Listening on http://0.0.0.0:8191"
so i copied the url, but the error below happened..
how do i get the url in the first place? thanks..
also if i batch downloading, do you also need the flaresolver link every line?

 File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          |             |      |    |        |             -> 'too many error responses'
          |             |      |    |        -> <class 'urllib3.exceptions.ResponseError'>
          |             |      |    -> SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer cer...
          |             |      -> '/g/338347/'
          |             -> <urllib3.connectionpool.HTTPSConnectionPool object at 0x043500D0>
          -> <class 'urllib3.exceptions.MaxRetryError'>
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nhentai.net', port=443): Max retries exceeded with url: /g/338347/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\Shi.no.iro\AppData\Loca...
         -> <code object <module> at 0x01ED7AB0, file "C:\Users\Shi.no.iro\AppData\Local\Programs\Python\Python38-32\Scripts\manga-py.exe\__...
  File "C:\Users\Shi.no.iro\AppData\Local\Programs\Python\Python38-32\Scripts\manga-py.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |        -> <function main at 0x0431B898>
    -> <module 'sys' (built-in)>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\manga_py\util.py", line 124, in main
    exit(run_util(args))
    |    |        -> {'url': 'https://nhentai.net/g/338347/', 'name': '', 'destination': 'D:/', 'no_progress': False, 'global_progress': False, 'argu...
    |    -> <function run_util at 0x0431B808>
    -> <built-in function exit>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\manga_py\util.py", line 82, in run_util
    _info = _run_util(args)
            |         -> {'url': 'https://nhentai.net/g/338347/', 'name': '', 'destination': 'D:/', 'no_progress': False, 'global_progress': False, 'argu...
            -> <function _run_util at 0x0431B778>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\manga_py\util.py", line 42, in _run_util
    Cli(args, _info).start()
    |   |     -> <manga_py.info.Info object at 0x0430F820>
    |   -> {'url': 'https://nhentai.net/g/338347/', 'name': '', 'destination': 'D:/', 'no_progress': False, 'global_progress': False, 'argu...
    -> <class 'manga_py.cli.Cli'>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\manga_py\cli\__init__.py", line 35, in start
    self.parser.init_provider(
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\manga_py\parser.py", line 38, in init_provider
    real_url = self.check_url(original_url)
               |              -> 'https://nhentai.net/g/338347/'
               -> <manga_py.parser.Parser object at 0x0430F850>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\manga_py\parser.py", line 64, in check_url
    with get(url, stream=True, proxies=proxies) as response:
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
           |              |           |         -> {'stream': True, 'proxies': None, 'allow_redirects': True}
           |              |           -> None
           |              -> 'https://nhentai.net/g/338347/'
           -> <function request at 0x04147388>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           |                      |           |      -> {'params': None, 'stream': True, 'proxies': None, 'allow_redirects': True}
           |                      |           -> 'https://nhentai.net/g/338347/'
           |                      -> 'get'
           -> <requests.sessions.Session object at 0x0430F9B8>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
           |         |       -> {'timeout': None, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': True, 'cert': None}
           |         -> <PreparedRequest [GET]>
           -> <requests.sessions.Session object at 0x0430F9B8>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
        |            |          -> {'timeout': None, 'verify': True, 'proxies': OrderedDict(), 'stream': True, 'cert': None}
        |            -> <PreparedRequest [GET]>
        -> <requests.adapters.HTTPAdapter object at 0x0430F940>
  File "c:\users\shi.no.iro\appdata\local\programs\python\python38-32\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
          |                   -> <PreparedRequest [GET]>
          -> <class 'requests.exceptions.SSLError'>
requests.exceptions.SSLError: HTTPSConnectionPool(host='nhentai.net', port=443): Max retries exceeded with url: /g/338347/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

**Comment by 1271** [comment]
Looking at the error - you just can't open the site. Maybe it's blocked in your country?

**Comment by ShinoIro** [comment]
> Looking at the error - you just can't open the site. Maybe it's blocked in your country?

yes, i may not use vpn over there, here's the error when i use vpn : 

    with http.get(url=url, headers=headers, cookies=cookies) as resp:
AttributeError: 'NoneType' object has no attribute 'get'

the command : manga-py https://nhentai.net/g/123456 -d D:/ --flare-solver-url http://127.0.0.1:8191

The flare solver : 
2022-05-08T23:05:49+07:00 INFO FlareSolverr v2.2.4
2022-05-08T23:05:49+07:00 INFO Testing web browser installation...
2022-05-08T23:05:59+07:00 INFO FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
2022-05-08T23:06:05+07:00 INFO Test successful
2022-05-08T23:06:05+07:00 INFO Listening on http://127.0.0.1:8191

**Comment by 1271** [comment]
> error when i use vpn 

Hm... Ok, thanks. I check it

**Comment by 1271** [comment]
Not sure if this will work, but you can try.
Unfortunately, CloudSolverr does not work for me at all (I don’t know what the reason is, but there is a timeout error all the time)

Please be aware that manga-py is not updated in pypi right now. You can use sources instead

**Comment by ShinoIro** [comment]
> Not sure if this will work, but you can try. Unfortunately, CloudSolverr does not work for me at all (I don’t know what the reason is, but there is a timeout error all the time)
> 
> Please be aware that manga-py is not updated in pypi right now. You can use sources instead

might try updating via source instead, 
but how do you update it manually?

**Comment by 1271** [comment]
You can download the zip archive and run it

`python manga.py`

instead of `manga-py`


Just don't forget that you will need to install dependencies if you were working inside venv:


`pip install -Ur requirements.txt`
